# Code generated by `typeddictgen`. DO NOT EDIT.
"""AdmissionregistrationV1ServiceReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class AdmissionregistrationV1ServiceReferenceType:
    name: str
    namespace: str
    path: str
    port: int
