# Code generated by `typeddictgen`. DO NOT EDIT.
"""AdmissionregistrationV1WebhookClientConfigType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.admissionregistration_v1_service_reference import AdmissionregistrationV1ServiceReferenceType


@dataclass
class AdmissionregistrationV1WebhookClientConfigType:
    caBundle: str
    service: AdmissionregistrationV1ServiceReferenceType
    url: str
