# Code generated by `typeddictgen`. DO NOT EDIT.
"""ApiextensionsV1WebhookClientConfigType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .apiextensions_v1_service_reference import ApiextensionsV1ServiceReferenceType


@dataclass
class ApiextensionsV1WebhookClientConfigType:
    ca_bundle: str
    service: ApiextensionsV1ServiceReferenceType
    url: str
