# Code generated by `typeddictgen`. DO NOT EDIT.
"""ApiregistrationV1ServiceReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class ApiregistrationV1ServiceReferenceType:
    name: str
    namespace: str
    port: int
