# Code generated by `typeddictgen`. DO NOT EDIT.
"""AuthenticationV1TokenRequestType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_token_request_spec import V1TokenRequestSpecType
from kubernetes_typed.client.models.v1_token_request_status import V1TokenRequestStatusType


@dataclass
class AuthenticationV1TokenRequestType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1TokenRequestSpecType
    status: V1TokenRequestStatusType
