# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EventListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .core_v1_event import CoreV1EventType
from .v1_list_meta import V1ListMetaType


@dataclass
class CoreV1EventListType:
    api_version: str
    items: List[CoreV1EventType]
    kind: str
    metadata: V1ListMetaType
