# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EventListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.core_v1_event import CoreV1EventType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class CoreV1EventListType:
    apiVersion: str
    items: List[CoreV1EventType]
    kind: str
    metadata: V1ListMetaType
