# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EventType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass
from kubernetes_typed.client.models.core_v1_event_series import CoreV1EventSeriesType
from kubernetes_typed.client.models.v1_event_source import V1EventSourceType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType


@dataclass
class CoreV1EventType:
    action: str
    apiVersion: str
    count: int
    eventTime: datetime.datetime
    firstTimestamp: datetime.datetime
    involvedObject: V1ObjectReferenceType
    kind: str
    lastTimestamp: datetime.datetime
    message: str
    metadata: V1ObjectMetaType
    reason: str
    related: V1ObjectReferenceType
    reportingComponent: str
    reportingInstance: str
    series: CoreV1EventSeriesType
    source: V1EventSourceType
    type: str
