# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EventType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


from .v1_object_reference import V1ObjectReferenceType
from .v1_object_meta import V1ObjectMetaType
from .core_v1_event_series import CoreV1EventSeriesType
from .v1_event_source import V1EventSourceType


@dataclass
class CoreV1EventType:
    action: str
    api_version: str
    count: int
    event_time: datetime.datetime
    first_timestamp: datetime.datetime
    involved_object: V1ObjectReferenceType
    kind: str
    last_timestamp: datetime.datetime
    message: str
    metadata: V1ObjectMetaType
    reason: str
    related: V1ObjectReferenceType
    reporting_component: str
    reporting_instance: str
    series: CoreV1EventSeriesType
    source: V1EventSourceType
    type: str
