# Code generated by `typeddictgen`. DO NOT EDIT.
"""EventsV1EventType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


from .v1_event_source import V1EventSourceType
from .v1_object_meta import V1ObjectMetaType
from .v1_object_reference import V1ObjectReferenceType
from .events_v1_event_series import EventsV1EventSeriesType


@dataclass
class EventsV1EventType:
    action: str
    api_version: str
    deprecated_count: int
    deprecated_first_timestamp: datetime.datetime
    deprecated_last_timestamp: datetime.datetime
    deprecated_source: V1EventSourceType
    event_time: datetime.datetime
    kind: str
    metadata: V1ObjectMetaType
    note: str
    reason: str
    regarding: V1ObjectReferenceType
    related: V1ObjectReferenceType
    reporting_controller: str
    reporting_instance: str
    series: EventsV1EventSeriesType
    type: str
