# Code generated by `typeddictgen`. DO NOT EDIT.
"""EventsV1EventListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .events_v1_event import EventsV1EventType
from .v1_list_meta import V1ListMetaType


@dataclass
class EventsV1EventListType:
    api_version: str
    items: List[EventsV1EventType]
    kind: str
    metadata: V1ListMetaType
