# Code generated by `typeddictgen`. DO NOT EDIT.
"""EventsV1EventListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.events_v1_event import EventsV1EventType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class EventsV1EventListType:
    apiVersion: str
    items: List[EventsV1EventType]
    kind: str
    metadata: V1ListMetaType
