# Code generated by `typeddictgen`. DO NOT EDIT.
"""EventsV1EventType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass
from kubernetes_typed.client.models.events_v1_event_series import EventsV1EventSeriesType
from kubernetes_typed.client.models.v1_event_source import V1EventSourceType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType


@dataclass
class EventsV1EventType:
    action: str
    apiVersion: str
    deprecatedCount: int
    deprecatedFirstTimestamp: datetime.datetime
    deprecatedLastTimestamp: datetime.datetime
    deprecatedSource: V1EventSourceType
    eventTime: datetime.datetime
    kind: str
    metadata: V1ObjectMetaType
    note: str
    reason: str
    regarding: V1ObjectReferenceType
    related: V1ObjectReferenceType
    reportingController: str
    reportingInstance: str
    series: EventsV1EventSeriesType
    type: str
