# Code generated by `typeddictgen`. DO NOT EDIT.
"""FlowcontrolV1SubjectType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_group_subject import V1GroupSubjectType
from kubernetes_typed.client.models.v1_service_account_subject import V1ServiceAccountSubjectType
from kubernetes_typed.client.models.v1_user_subject import V1UserSubjectType


@dataclass
class FlowcontrolV1SubjectType:
    group: V1GroupSubjectType
    kind: str
    serviceAccount: V1ServiceAccountSubjectType
    user: V1UserSubjectType
