# Code generated by `typeddictgen`. DO NOT EDIT.
"""RbacV1SubjectType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class RbacV1SubjectType:
    apiGroup: str
    kind: str
    name: str
    namespace: str
