# Code generated by `typeddictgen`. DO NOT EDIT.
"""StorageV1TokenRequestType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class StorageV1TokenRequestType:
    audience: str
    expiration_seconds: int
