# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIGroupType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_group_version_for_discovery import V1GroupVersionForDiscoveryType
from kubernetes_typed.client.models.v1_server_address_by_client_cidr import V1ServerAddressByClientCIDRType


@dataclass
class V1APIGroupType:
    apiVersion: str
    kind: str
    name: str
    preferredVersion: V1GroupVersionForDiscoveryType
    serverAddressByClientCIDRs: List[V1ServerAddressByClientCIDRType]
    versions: List[V1GroupVersionForDiscoveryType]
