# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIResourceListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_api_resource import V1APIResourceType


@dataclass
class V1APIResourceListType:
    apiVersion: str
    groupVersion: str
    kind: str
    resources: List[V1APIResourceType]
