# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AuditAnnotationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1AuditAnnotationType:
    key: str
    valueExpression: str
