# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIServiceSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.apiregistration_v1_service_reference import ApiregistrationV1ServiceReferenceType


@dataclass
class V1APIServiceSpecType:
    caBundle: str
    group: str
    groupPriorityMinimum: int
    insecureSkipTLSVerify: bool
    service: ApiregistrationV1ServiceReferenceType
    version: str
    versionPriority: int
