# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AzureFileVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1AzureFileVolumeSourceType:
    readOnly: bool
    secretName: str
    shareName: str
