# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AzureFilePersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1AzureFilePersistentVolumeSourceType:
    read_only: bool
    secret_name: str
    secret_namespace: str
    share_name: str
