# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIGroupListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_api_group import V1APIGroupType


@dataclass
class V1APIGroupListType:
    apiVersion: str
    groups: List[V1APIGroupType]
    kind: str
