# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AggregationRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1AggregationRuleType:
    cluster_role_selectors: List[V1LabelSelectorType]
