# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AttachedVolumeType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1AttachedVolumeType:
    device_path: str
    name: str
