# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AffinityType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_affinity import V1NodeAffinityType
from kubernetes_typed.client.models.v1_pod_affinity import V1PodAffinityType
from kubernetes_typed.client.models.v1_pod_anti_affinity import V1PodAntiAffinityType


@dataclass
class V1AffinityType:
    nodeAffinity: V1NodeAffinityType
    podAffinity: V1PodAffinityType
    podAntiAffinity: V1PodAntiAffinityType
