# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AzureFilePersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1AzureFilePersistentVolumeSourceType:
    readOnly: bool
    secretName: str
    secretNamespace: str
    shareName: str
