# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIServiceListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_api_service import V1APIServiceType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1APIServiceListType:
    api_version: str
    items: List[V1APIServiceType]
    kind: str
    metadata: V1ListMetaType
