# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIGroupType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_group_version_for_discovery import V1GroupVersionForDiscoveryType
from .v1_server_address_by_client_cidr import V1ServerAddressByClientCIDRType


@dataclass
class V1APIGroupType:
    api_version: str
    kind: str
    name: str
    preferred_version: V1GroupVersionForDiscoveryType
    server_address_by_client_cid_rs: List[V1ServerAddressByClientCIDRType]
    versions: List[V1GroupVersionForDiscoveryType]
