# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AzureDiskVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1AzureDiskVolumeSourceType:
    caching_mode: str
    disk_name: str
    disk_uri: str
    fs_type: str
    kind: str
    read_only: bool
