# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AzureFileVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1AzureFileVolumeSourceType:
    read_only: bool
    secret_name: str
    share_name: str
