# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIVersionsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_server_address_by_client_cidr import V1ServerAddressByClientCIDRType


@dataclass
class V1APIVersionsType:
    api_version: str
    kind: str
    server_address_by_client_cid_rs: List[V1ServerAddressByClientCIDRType]
    versions: List[str]
