# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIServiceListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_api_service import V1APIServiceType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1APIServiceListType:
    apiVersion: str
    items: List[V1APIServiceType]
    kind: str
    metadata: V1ListMetaType
