# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AWSElasticBlockStoreVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1AWSElasticBlockStoreVolumeSourceType:
    fsType: str
    partition: int
    readOnly: bool
    volumeID: str
