# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIVersionsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_server_address_by_client_cidr import V1ServerAddressByClientCIDRType


@dataclass
class V1APIVersionsType:
    apiVersion: str
    kind: str
    serverAddressByClientCIDRs: List[V1ServerAddressByClientCIDRType]
    versions: List[str]
