# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AWSElasticBlockStoreVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1AWSElasticBlockStoreVolumeSourceType:
    fs_type: str
    partition: int
    read_only: bool
    volume_id: str
