# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIResourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1APIResourceType:
    categories: List[str]
    group: str
    kind: str
    name: str
    namespaced: bool
    short_names: List[str]
    singular_name: str
    storage_version_hash: str
    verbs: List[str]
    version: str
