# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AggregationRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType


@dataclass
class V1AggregationRuleType:
    clusterRoleSelectors: List[V1LabelSelectorType]
