# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIServiceStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_api_service_condition import V1APIServiceConditionType


@dataclass
class V1APIServiceStatusType:
    conditions: List[V1APIServiceConditionType]
