# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIServiceSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .apiregistration_v1_service_reference import ApiregistrationV1ServiceReferenceType


@dataclass
class V1APIServiceSpecType:
    ca_bundle: str
    group: str
    group_priority_minimum: int
    insecure_skip_tls_verify: bool
    service: ApiregistrationV1ServiceReferenceType
    version: str
    version_priority: int
