# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AzureDiskVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1AzureDiskVolumeSourceType:
    cachingMode: str
    diskName: str
    diskURI: str
    fsType: str
    kind: str
    readOnly: bool
