# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AffinityType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_node_affinity import V1NodeAffinityType
from .v1_pod_affinity import V1PodAffinityType
from .v1_pod_anti_affinity import V1PodAntiAffinityType


@dataclass
class V1AffinityType:
    node_affinity: V1NodeAffinityType
    pod_affinity: V1PodAffinityType
    pod_anti_affinity: V1PodAntiAffinityType
