# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1BoundObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1BoundObjectReferenceType:
    apiVersion: str
    kind: str
    name: str
    uid: str
