# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_csi_node_driver import V1CSINodeDriverType


@dataclass
class V1CSINodeSpecType:
    drivers: List[V1CSINodeDriverType]
