# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_csi_driver_spec import V1CSIDriverSpecType


@dataclass
class V1CSIDriverType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CSIDriverSpecType
