# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterRoleBindingType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.rbac_v1_subject import RbacV1SubjectType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_role_ref import V1RoleRefType


@dataclass
class V1ClusterRoleBindingType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    roleRef: V1RoleRefType
    subjects: List[RbacV1SubjectType]
