# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerPortType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ContainerPortType:
    container_port: int
    host_ip: str
    host_port: int
    name: str
    protocol: str
