# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapEnvSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ConfigMapEnvSourceType:
    name: str
    optional: bool
