# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIStorageCapacityListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_csi_storage_capacity import V1CSIStorageCapacityType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1CSIStorageCapacityListType:
    apiVersion: str
    items: List[V1CSIStorageCapacityType]
    kind: str
    metadata: V1ListMetaType
