# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CrossVersionObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1CrossVersionObjectReferenceType:
    api_version: str
    kind: str
    name: str
