# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceValidationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_json_schema_props import V1JSONSchemaPropsType


@dataclass
class V1CustomResourceValidationType:
    open_apiv3_schema: V1JSONSchemaPropsType
