# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentConditionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ComponentConditionType:
    error: str
    message: str
    status: str
    type: str
