# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerUserType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_linux_container_user import V1LinuxContainerUserType


@dataclass
class V1ContainerUserType:
    linux: V1LinuxContainerUserType
