# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerPortType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ContainerPortType:
    containerPort: int
    hostIP: str
    hostPort: int
    name: str
    protocol: str
