# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_custom_resource_definition import V1CustomResourceDefinitionType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1CustomResourceDefinitionListType:
    apiVersion: str
    items: List[V1CustomResourceDefinitionType]
    kind: str
    metadata: V1ListMetaType
