# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_cron_job import V1CronJobType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1CronJobListType:
    apiVersion: str
    items: List[V1CronJobType]
    kind: str
    metadata: V1ListMetaType
