# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_certificate_signing_request_spec import V1CertificateSigningRequestSpecType
from .v1_certificate_signing_request_status import V1CertificateSigningRequestStatusType


@dataclass
class V1CertificateSigningRequestType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CertificateSigningRequestSpecType
    status: V1CertificateSigningRequestStatusType
