# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapProjectionType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_key_to_path import V1KeyToPathType


@dataclass
class V1ConfigMapProjectionType:
    items: List[V1KeyToPathType]
    name: str
    optional: bool
