# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_job_template_spec import V1JobTemplateSpecType


@dataclass
class V1CronJobSpecType:
    concurrency_policy: str
    failed_jobs_history_limit: int
    job_template: V1JobTemplateSpecType
    schedule: str
    starting_deadline_seconds: int
    successful_jobs_history_limit: int
    suspend: bool
    time_zone: str
