# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterRoleListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_cluster_role import V1ClusterRoleType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1ClusterRoleListType:
    apiVersion: str
    items: List[V1ClusterRoleType]
    kind: str
    metadata: V1ListMetaType
