# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_custom_resource_definition_condition import V1CustomResourceDefinitionConditionType
from kubernetes_typed.client.models.v1_custom_resource_definition_names import V1CustomResourceDefinitionNamesType


@dataclass
class V1CustomResourceDefinitionStatusType:
    acceptedNames: V1CustomResourceDefinitionNamesType
    conditions: List[V1CustomResourceDefinitionConditionType]
    storedVersions: List[str]
