# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeDriverType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_volume_node_resources import V1VolumeNodeResourcesType


@dataclass
class V1CSINodeDriverType:
    allocatable: V1VolumeNodeResourcesType
    name: str
    node_id: str
    topology_keys: List[str]
