# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_certificate_signing_request_spec import V1CertificateSigningRequestSpecType
from kubernetes_typed.client.models.v1_certificate_signing_request_status import V1CertificateSigningRequestStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1CertificateSigningRequestType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CertificateSigningRequestSpecType
    status: V1CertificateSigningRequestStatusType
