# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerStateTerminatedType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1ContainerStateTerminatedType:
    containerID: str
    exitCode: int
    finishedAt: datetime.datetime
    message: str
    reason: str
    signal: int
    startedAt: datetime.datetime
