# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceSubresourceScaleType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1CustomResourceSubresourceScaleType:
    labelSelectorPath: str
    specReplicasPath: str
    statusReplicasPath: str
