# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.storage_v1_token_request import StorageV1TokenRequestType


@dataclass
class V1CSIDriverSpecType:
    attachRequired: bool
    fsGroupPolicy: str
    podInfoOnMount: bool
    requiresRepublish: bool
    seLinuxMount: bool
    storageCapacity: bool
    tokenRequests: List[StorageV1TokenRequestType]
    volumeLifecycleModes: List[str]
