# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapNodeConfigSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ConfigMapNodeConfigSourceType:
    kubeletConfigKey: str
    name: str
    namespace: str
    resourceVersion: str
    uid: str
