# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentStatusListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_component_status import V1ComponentStatusType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1ComponentStatusListType:
    apiVersion: str
    items: List[V1ComponentStatusType]
    kind: str
    metadata: V1ListMetaType
