# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CinderVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1CinderVolumeSourceType:
    fs_type: str
    read_only: bool
    secret_ref: V1LocalObjectReferenceType
    volume_id: str
