# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CinderPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_secret_reference import V1SecretReferenceType


@dataclass
class V1CinderPersistentVolumeSourceType:
    fsType: str
    readOnly: bool
    secretRef: V1SecretReferenceType
    volumeID: str
