# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClaimSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ClaimSourceType:
    resource_claim_name: str
    resource_claim_template_name: str
