# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterTrustBundleProjectionType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType


@dataclass
class V1ClusterTrustBundleProjectionType:
    labelSelector: V1LabelSelectorType
    name: str
    optional: bool
    path: str
    signerName: str
