# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ControllerRevisionListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_controller_revision import V1ControllerRevisionType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1ControllerRevisionListType:
    api_version: str
    items: List[V1ControllerRevisionType]
    kind: str
    metadata: V1ListMetaType
