# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CinderVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1CinderVolumeSourceType:
    fsType: str
    readOnly: bool
    secretRef: V1LocalObjectReferenceType
    volumeID: str
