# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_csi_driver import V1CSIDriverType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1CSIDriverListType:
    apiVersion: str
    items: List[V1CSIDriverType]
    kind: str
    metadata: V1ListMetaType
