# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_custom_resource_definition_spec import V1CustomResourceDefinitionSpecType
from kubernetes_typed.client.models.v1_custom_resource_definition_status import V1CustomResourceDefinitionStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1CustomResourceDefinitionType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CustomResourceDefinitionSpecType
    status: V1CustomResourceDefinitionStatusType
