# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_component_condition import V1ComponentConditionType
from .v1_object_meta import V1ObjectMetaType


@dataclass
class V1ComponentStatusType:
    api_version: str
    conditions: List[V1ComponentConditionType]
    kind: str
    metadata: V1ObjectMetaType
