# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerStateRunningType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1ContainerStateRunningType:
    started_at: datetime.datetime
