# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass
from typing import List

from .v1_object_reference import V1ObjectReferenceType


@dataclass
class V1CronJobStatusType:
    active: List[V1ObjectReferenceType]
    last_schedule_time: datetime.datetime
    last_successful_time: datetime.datetime
