# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterTrustBundleProjectionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1ClusterTrustBundleProjectionType:
    label_selector: V1LabelSelectorType
    name: str
    optional: bool
    path: str
    signer_name: str
