# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapKeySelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ConfigMapKeySelectorType:
    key: str
    name: str
    optional: bool
