# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterRoleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_aggregation_rule import V1AggregationRuleType
from .v1_object_meta import V1ObjectMetaType
from .v1_policy_rule import V1PolicyRuleType


@dataclass
class V1ClusterRoleType:
    aggregation_rule: V1AggregationRuleType
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    rules: List[V1PolicyRuleType]
