# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_secret_reference import V1SecretReferenceType


@dataclass
class V1CSIPersistentVolumeSourceType:
    controllerExpandSecretRef: V1SecretReferenceType
    controllerPublishSecretRef: V1SecretReferenceType
    driver: str
    fsType: str
    nodeExpandSecretRef: V1SecretReferenceType
    nodePublishSecretRef: V1SecretReferenceType
    nodeStageSecretRef: V1SecretReferenceType
    readOnly: bool
    volumeAttributes: Dict[str, str]
    volumeHandle: str
