# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CapabilitiesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1CapabilitiesType:
    add: List[str]
    drop: List[str]
