# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClientIPConfigType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ClientIPConfigType:
    timeout_seconds: int
