# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CephFSPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_secret_reference import V1SecretReferenceType


@dataclass
class V1CephFSPersistentVolumeSourceType:
    monitors: List[str]
    path: str
    read_only: bool
    secret_file: str
    secret_ref: V1SecretReferenceType
    user: str
