# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeDriverType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_volume_node_resources import V1VolumeNodeResourcesType


@dataclass
class V1CSINodeDriverType:
    allocatable: V1VolumeNodeResourcesType
    name: str
    nodeID: str
    topologyKeys: List[str]
