# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterRoleBindingType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_object_meta import V1ObjectMetaType
from .v1_role_ref import V1RoleRefType
from .rbac_v1_subject import RbacV1SubjectType


@dataclass
class V1ClusterRoleBindingType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    role_ref: V1RoleRefType
    subjects: List[RbacV1SubjectType]
