# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerImageType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1ContainerImageType:
    names: List[str]
    size_bytes: int
