# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CephFSPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_secret_reference import V1SecretReferenceType


@dataclass
class V1CephFSPersistentVolumeSourceType:
    monitors: List[str]
    path: str
    readOnly: bool
    secretFile: str
    secretRef: V1SecretReferenceType
    user: str
