# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_csi_driver_spec import V1CSIDriverSpecType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1CSIDriverType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CSIDriverSpecType
