# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict

from .v1_container_state import V1ContainerStateType
from .v1_resource_requirements import V1ResourceRequirementsType


@dataclass
class V1ContainerStatusType:
    allocated_resources: Dict[str, str]
    container_id: str
    image: str
    image_id: str
    last_state: V1ContainerStateType
    name: str
    ready: bool
    resources: V1ResourceRequirementsType
    restart_count: int
    started: bool
    state: V1ContainerStateType
