# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionVersionType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_custom_resource_column_definition import V1CustomResourceColumnDefinitionType
from kubernetes_typed.client.models.v1_custom_resource_subresources import V1CustomResourceSubresourcesType
from kubernetes_typed.client.models.v1_custom_resource_validation import V1CustomResourceValidationType
from kubernetes_typed.client.models.v1_selectable_field import V1SelectableFieldType


@dataclass
class V1CustomResourceDefinitionVersionType:
    additionalPrinterColumns: List[V1CustomResourceColumnDefinitionType]
    deprecated: bool
    deprecationWarning: str
    name: str
    schema: V1CustomResourceValidationType
    selectableFields: List[V1SelectableFieldType]
    served: bool
    storage: bool
    subresources: V1CustomResourceSubresourcesType
