# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_csi_node import V1CSINodeType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1CSINodeListType:
    apiVersion: str
    items: List[V1CSINodeType]
    kind: str
    metadata: V1ListMetaType
