# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_component_condition import V1ComponentConditionType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1ComponentStatusType:
    apiVersion: str
    conditions: List[V1ComponentConditionType]
    kind: str
    metadata: V1ObjectMetaType
