# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_cron_job_spec import V1CronJobSpecType
from .v1_cron_job_status import V1CronJobStatusType


@dataclass
class V1CronJobType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CronJobSpecType
    status: V1CronJobStatusType
