# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterRoleType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_aggregation_rule import V1AggregationRuleType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_policy_rule import V1PolicyRuleType


@dataclass
class V1ClusterRoleType:
    aggregationRule: V1AggregationRuleType
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    rules: List[V1PolicyRuleType]
