# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterRoleBindingListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_cluster_role_binding import V1ClusterRoleBindingType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1ClusterRoleBindingListType:
    apiVersion: str
    items: List[V1ClusterRoleBindingType]
    kind: str
    metadata: V1ListMetaType
