# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_csi_node_driver import V1CSINodeDriverType


@dataclass
class V1CSINodeSpecType:
    drivers: List[V1CSINodeDriverType]
