# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict

from .v1_object_meta import V1ObjectMetaType


@dataclass
class V1ConfigMapType:
    api_version: str
    binary_data: Dict[str, str]
    data: Dict[str, str]
    immutable: bool
    kind: str
    metadata: V1ObjectMetaType
