# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .storage_v1_token_request import StorageV1TokenRequestType


@dataclass
class V1CSIDriverSpecType:
    attach_required: bool
    fs_group_policy: str
    pod_info_on_mount: bool
    requires_republish: bool
    se_linux_mount: bool
    storage_capacity: bool
    token_requests: List[StorageV1TokenRequestType]
    volume_lifecycle_modes: List[str]
