# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_config_map import V1ConfigMapType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1ConfigMapListType:
    apiVersion: str
    items: List[V1ConfigMapType]
    kind: str
    metadata: V1ListMetaType
