# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceSubresourcesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_custom_resource_subresource_scale import V1CustomResourceSubresourceScaleType


@dataclass
class V1CustomResourceSubresourcesType:
    scale: V1CustomResourceSubresourceScaleType
    status: object
