# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentStatusListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_component_status import V1ComponentStatusType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1ComponentStatusListType:
    api_version: str
    items: List[V1ComponentStatusType]
    kind: str
    metadata: V1ListMetaType
