# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestConditionType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1CertificateSigningRequestConditionType:
    last_transition_time: datetime.datetime
    last_update_time: datetime.datetime
    message: str
    reason: str
    status: str
    type: str
