# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1CSIVolumeSourceType:
    driver: str
    fsType: str
    nodePublishSecretRef: V1LocalObjectReferenceType
    readOnly: bool
    volumeAttributes: Dict[str, str]
