# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_certificate_signing_request import V1CertificateSigningRequestType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1CertificateSigningRequestListType:
    api_version: str
    items: List[V1CertificateSigningRequestType]
    kind: str
    metadata: V1ListMetaType
