# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIStorageCapacityType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1CSIStorageCapacityType:
    apiVersion: str
    capacity: str
    kind: str
    maximumVolumeSize: str
    metadata: V1ObjectMetaType
    nodeTopology: V1LabelSelectorType
    storageClassName: str
