# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CephFSVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1CephFSVolumeSourceType:
    monitors: List[str]
    path: str
    read_only: bool
    secret_file: str
    secret_ref: V1LocalObjectReferenceType
    user: str
