# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_config_map import V1ConfigMapType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1ConfigMapListType:
    api_version: str
    items: List[V1ConfigMapType]
    kind: str
    metadata: V1ListMetaType
