# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_certificate_signing_request_condition import V1CertificateSigningRequestConditionType


@dataclass
class V1CertificateSigningRequestStatusType:
    certificate: str
    conditions: List[V1CertificateSigningRequestConditionType]
