# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionVersionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_custom_resource_column_definition import V1CustomResourceColumnDefinitionType
from .v1_custom_resource_validation import V1CustomResourceValidationType
from .v1_custom_resource_subresources import V1CustomResourceSubresourcesType


@dataclass
class V1CustomResourceDefinitionVersionType:
    additional_printer_columns: List[V1CustomResourceColumnDefinitionType]
    deprecated: bool
    deprecation_warning: str
    name: str
    schema: V1CustomResourceValidationType
    served: bool
    storage: bool
    subresources: V1CustomResourceSubresourcesType
