# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_csi_node_spec import V1CSINodeSpecType


@dataclass
class V1CSINodeType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CSINodeSpecType
