# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict

from .v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1CSIVolumeSourceType:
    driver: str
    fs_type: str
    node_publish_secret_ref: V1LocalObjectReferenceType
    read_only: bool
    volume_attributes: Dict[str, str]
