# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerResizePolicyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ContainerResizePolicyType:
    resource_name: str
    restart_policy: str
