# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceValidationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_json_schema_props import V1JSONSchemaPropsType


@dataclass
class V1CustomResourceValidationType:
    openAPIV3Schema: V1JSONSchemaPropsType
