# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_custom_resource_conversion import V1CustomResourceConversionType
from .v1_custom_resource_definition_names import V1CustomResourceDefinitionNamesType
from .v1_custom_resource_definition_version import V1CustomResourceDefinitionVersionType


@dataclass
class V1CustomResourceDefinitionSpecType:
    conversion: V1CustomResourceConversionType
    group: str
    names: V1CustomResourceDefinitionNamesType
    preserve_unknown_fields: bool
    scope: str
    versions: List[V1CustomResourceDefinitionVersionType]
