# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType


@dataclass
class V1CronJobStatusType:
    active: List[V1ObjectReferenceType]
    lastScheduleTime: datetime.datetime
    lastSuccessfulTime: datetime.datetime
