# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerImageType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1ContainerImageType:
    names: List[str]
    sizeBytes: int
