# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_custom_resource_definition_spec import V1CustomResourceDefinitionSpecType
from .v1_custom_resource_definition_status import V1CustomResourceDefinitionStatusType


@dataclass
class V1CustomResourceDefinitionType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1CustomResourceDefinitionSpecType
    status: V1CustomResourceDefinitionStatusType
