# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_container_state import V1ContainerStateType
from kubernetes_typed.client.models.v1_container_user import V1ContainerUserType
from kubernetes_typed.client.models.v1_resource_requirements import V1ResourceRequirementsType
from kubernetes_typed.client.models.v1_resource_status import V1ResourceStatusType
from kubernetes_typed.client.models.v1_volume_mount_status import V1VolumeMountStatusType


@dataclass
class V1ContainerStatusType:
    allocatedResources: Dict[str, str]
    allocatedResourcesStatus: List[V1ResourceStatusType]
    containerID: str
    image: str
    imageID: str
    lastState: V1ContainerStateType
    name: str
    ready: bool
    resources: V1ResourceRequirementsType
    restartCount: int
    started: bool
    state: V1ContainerStateType
    user: V1ContainerUserType
    volumeMounts: List[V1VolumeMountStatusType]
