# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_custom_resource_definition_names import V1CustomResourceDefinitionNamesType
from .v1_custom_resource_definition_condition import V1CustomResourceDefinitionConditionType


@dataclass
class V1CustomResourceDefinitionStatusType:
    accepted_names: V1CustomResourceDefinitionNamesType
    conditions: List[V1CustomResourceDefinitionConditionType]
    stored_versions: List[str]
