# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ControllerRevisionListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_controller_revision import V1ControllerRevisionType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1ControllerRevisionListType:
    apiVersion: str
    items: List[V1ControllerRevisionType]
    kind: str
    metadata: V1ListMetaType
