# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CinderPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_secret_reference import V1SecretReferenceType


@dataclass
class V1CinderPersistentVolumeSourceType:
    fs_type: str
    read_only: bool
    secret_ref: V1SecretReferenceType
    volume_id: str
