# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass


@dataclass
class V1CertificateSigningRequestSpecType:
    expirationSeconds: int
    extra: Dict[str, List[str]]
    groups: List[str]
    request: str
    signerName: str
    uid: str
    usages: List[str]
    username: str
