# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_csi_driver import V1CSIDriverType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1CSIDriverListType:
    api_version: str
    items: List[V1CSIDriverType]
    kind: str
    metadata: V1ListMetaType
