# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict, List


@dataclass
class V1CertificateSigningRequestSpecType:
    expiration_seconds: int
    extra: Dict[str, List[str]]
    groups: List[str]
    request: str
    signer_name: str
    uid: str
    usages: List[str]
    username: str
