# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapNodeConfigSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ConfigMapNodeConfigSourceType:
    kubelet_config_key: str
    name: str
    namespace: str
    resource_version: str
    uid: str
