# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_job_template_spec import V1JobTemplateSpecType


@dataclass
class V1CronJobSpecType:
    concurrencyPolicy: str
    failedJobsHistoryLimit: int
    jobTemplate: V1JobTemplateSpecType
    schedule: str
    startingDeadlineSeconds: int
    successfulJobsHistoryLimit: int
    suspend: bool
    timeZone: str
