# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionNamesType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1CustomResourceDefinitionNamesType:
    categories: List[str]
    kind: str
    listKind: str
    plural: str
    shortNames: List[str]
    singular: str
