# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CephFSVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1CephFSVolumeSourceType:
    monitors: List[str]
    path: str
    readOnly: bool
    secretFile: str
    secretRef: V1LocalObjectReferenceType
    user: str
