# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIStorageCapacityListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_csi_storage_capacity import V1CSIStorageCapacityType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1CSIStorageCapacityListType:
    api_version: str
    items: List[V1CSIStorageCapacityType]
    kind: str
    metadata: V1ListMetaType
