# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionNamesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1CustomResourceDefinitionNamesType:
    categories: List[str]
    kind: str
    list_kind: str
    plural: str
    short_names: List[str]
    singular: str
