# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_daemon_set import V1DaemonSetType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1DaemonSetListType:
    apiVersion: str
    items: List[V1DaemonSetType]
    kind: str
    metadata: V1ListMetaType
