# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_daemon_set_condition import V1DaemonSetConditionType


@dataclass
class V1DaemonSetStatusType:
    collisionCount: int
    conditions: List[V1DaemonSetConditionType]
    currentNumberScheduled: int
    desiredNumberScheduled: int
    numberAvailable: int
    numberMisscheduled: int
    numberReady: int
    numberUnavailable: int
    observedGeneration: int
    updatedNumberScheduled: int
