# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DownwardAPIProjectionType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_downward_api_volume_file import V1DownwardAPIVolumeFileType


@dataclass
class V1DownwardAPIProjectionType:
    items: List[V1DownwardAPIVolumeFileType]
