# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_deployment_condition import V1DeploymentConditionType


@dataclass
class V1DeploymentStatusType:
    availableReplicas: int
    collisionCount: int
    conditions: List[V1DeploymentConditionType]
    observedGeneration: int
    readyReplicas: int
    replicas: int
    unavailableReplicas: int
    updatedReplicas: int
