# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_label_selector import V1LabelSelectorType
from .v1_deployment_strategy import V1DeploymentStrategyType
from .v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1DeploymentSpecType:
    min_ready_seconds: int
    paused: bool
    progress_deadline_seconds: int
    replicas: int
    revision_history_limit: int
    selector: V1LabelSelectorType
    strategy: V1DeploymentStrategyType
    template: V1PodTemplateSpecType
