# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DownwardAPIVolumeFileType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_field_selector import V1ObjectFieldSelectorType
from kubernetes_typed.client.models.v1_resource_field_selector import V1ResourceFieldSelectorType


@dataclass
class V1DownwardAPIVolumeFileType:
    fieldRef: V1ObjectFieldSelectorType
    mode: int
    path: str
    resourceFieldRef: V1ResourceFieldSelectorType
