# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_daemon_set import V1DaemonSetType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1DaemonSetListType:
    api_version: str
    items: List[V1DaemonSetType]
    kind: str
    metadata: V1ListMetaType
