# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentStrategyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_rolling_update_deployment import V1RollingUpdateDeploymentType


@dataclass
class V1DeploymentStrategyType:
    rolling_update: V1RollingUpdateDeploymentType
    type: str
