# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DownwardAPIVolumeFileType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_field_selector import V1ObjectFieldSelectorType
from .v1_resource_field_selector import V1ResourceFieldSelectorType


@dataclass
class V1DownwardAPIVolumeFileType:
    field_ref: V1ObjectFieldSelectorType
    mode: int
    path: str
    resource_field_ref: V1ResourceFieldSelectorType
