# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_daemon_set_condition import V1DaemonSetConditionType


@dataclass
class V1DaemonSetStatusType:
    collision_count: int
    conditions: List[V1DaemonSetConditionType]
    current_number_scheduled: int
    desired_number_scheduled: int
    number_available: int
    number_misscheduled: int
    number_ready: int
    number_unavailable: int
    observed_generation: int
    updated_number_scheduled: int
