# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_deployment import V1DeploymentType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1DeploymentListType:
    apiVersion: str
    items: List[V1DeploymentType]
    kind: str
    metadata: V1ListMetaType
