# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_label_selector import V1LabelSelectorType
from .v1_pod_template_spec import V1PodTemplateSpecType
from .v1_daemon_set_update_strategy import V1DaemonSetUpdateStrategyType


@dataclass
class V1DaemonSetSpecType:
    min_ready_seconds: int
    revision_history_limit: int
    selector: V1LabelSelectorType
    template: V1PodTemplateSpecType
    update_strategy: V1DaemonSetUpdateStrategyType
