# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetUpdateStrategyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_rolling_update_daemon_set import V1RollingUpdateDaemonSetType


@dataclass
class V1DaemonSetUpdateStrategyType:
    rolling_update: V1RollingUpdateDaemonSetType
    type: str
