# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeleteOptionsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_preconditions import V1PreconditionsType


@dataclass
class V1DeleteOptionsType:
    apiVersion: str
    dryRun: List[str]
    gracePeriodSeconds: int
    kind: str
    orphanDependents: bool
    preconditions: V1PreconditionsType
    propagationPolicy: str
