# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_daemon_set_spec import V1DaemonSetSpecType
from kubernetes_typed.client.models.v1_daemon_set_status import V1DaemonSetStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1DaemonSetType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1DaemonSetSpecType
    status: V1DaemonSetStatusType
