# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentStrategyType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_rolling_update_deployment import V1RollingUpdateDeploymentType


@dataclass
class V1DeploymentStrategyType:
    rollingUpdate: V1RollingUpdateDeploymentType
    type: str
