# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_deployment_strategy import V1DeploymentStrategyType
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1DeploymentSpecType:
    minReadySeconds: int
    paused: bool
    progressDeadlineSeconds: int
    replicas: int
    revisionHistoryLimit: int
    selector: V1LabelSelectorType
    strategy: V1DeploymentStrategyType
    template: V1PodTemplateSpecType
