# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_deployment import V1DeploymentType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1DeploymentListType:
    api_version: str
    items: List[V1DeploymentType]
    kind: str
    metadata: V1ListMetaType
