# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_deployment_condition import V1DeploymentConditionType


@dataclass
class V1DeploymentStatusType:
    available_replicas: int
    collision_count: int
    conditions: List[V1DeploymentConditionType]
    observed_generation: int
    ready_replicas: int
    replicas: int
    unavailable_replicas: int
    updated_replicas: int
