# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_deployment_spec import V1DeploymentSpecType
from kubernetes_typed.client.models.v1_deployment_status import V1DeploymentStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1DeploymentType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1DeploymentSpecType
    status: V1DeploymentStatusType
