# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentConditionType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1DeploymentConditionType:
    lastTransitionTime: datetime.datetime
    lastUpdateTime: datetime.datetime
    message: str
    reason: str
    status: str
    type: str
