# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_endpoint_conditions import V1EndpointConditionsType
from kubernetes_typed.client.models.v1_endpoint_hints import V1EndpointHintsType
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType


@dataclass
class V1EndpointType:
    addresses: List[str]
    conditions: V1EndpointConditionsType
    deprecatedTopology: Dict[str, str]
    hints: V1EndpointHintsType
    hostname: str
    nodeName: str
    targetRef: V1ObjectReferenceType
    zone: str
