# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvVarSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_config_map_key_selector import V1ConfigMapKeySelectorType
from kubernetes_typed.client.models.v1_object_field_selector import V1ObjectFieldSelectorType
from kubernetes_typed.client.models.v1_resource_field_selector import V1ResourceFieldSelectorType
from kubernetes_typed.client.models.v1_secret_key_selector import V1SecretKeySelectorType


@dataclass
class V1EnvVarSourceType:
    configMapKeyRef: V1ConfigMapKeySelectorType
    fieldRef: V1ObjectFieldSelectorType
    resourceFieldRef: V1ResourceFieldSelectorType
    secretKeyRef: V1SecretKeySelectorType
