# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointAddressType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType


@dataclass
class V1EndpointAddressType:
    hostname: str
    ip: str
    nodeName: str
    targetRef: V1ObjectReferenceType
