# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ExecActionType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1ExecActionType:
    command: List[str]
