# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointConditionsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1EndpointConditionsType:
    ready: bool
    serving: bool
    terminating: bool
