# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EmptyDirVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1EmptyDirVolumeSourceType:
    medium: str
    size_limit: str
