# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EphemeralVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_persistent_volume_claim_template import V1PersistentVolumeClaimTemplateType


@dataclass
class V1EphemeralVolumeSourceType:
    volume_claim_template: V1PersistentVolumeClaimTemplateType
