# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointsListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_endpoints import V1EndpointsType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1EndpointsListType:
    apiVersion: str
    items: List[V1EndpointsType]
    kind: str
    metadata: V1ListMetaType
