# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointSliceListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_endpoint_slice import V1EndpointSliceType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1EndpointSliceListType:
    apiVersion: str
    items: List[V1EndpointSliceType]
    kind: str
    metadata: V1ListMetaType
