# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointSubsetType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.core_v1_endpoint_port import CoreV1EndpointPortType
from kubernetes_typed.client.models.v1_endpoint_address import V1EndpointAddressType


@dataclass
class V1EndpointSubsetType:
    addresses: List[V1EndpointAddressType]
    notReadyAddresses: List[V1EndpointAddressType]
    ports: List[CoreV1EndpointPortType]
