# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointSubsetType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_endpoint_address import V1EndpointAddressType
from .core_v1_endpoint_port import CoreV1EndpointPortType


@dataclass
class V1EndpointSubsetType:
    addresses: List[V1EndpointAddressType]
    not_ready_addresses: List[V1EndpointAddressType]
    ports: List[CoreV1EndpointPortType]
