# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_endpoint_subset import V1EndpointSubsetType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1EndpointsType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    subsets: List[V1EndpointSubsetType]
