# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_object_meta import V1ObjectMetaType
from .v1_endpoint_subset import V1EndpointSubsetType


@dataclass
class V1EndpointsType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    subsets: List[V1EndpointSubsetType]
