# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointHintsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_for_zone import V1ForZoneType


@dataclass
class V1EndpointHintsType:
    forZones: List[V1ForZoneType]
