# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointSliceListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_endpoint_slice import V1EndpointSliceType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1EndpointSliceListType:
    api_version: str
    items: List[V1EndpointSliceType]
    kind: str
    metadata: V1ListMetaType
