# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointSliceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.discovery_v1_endpoint_port import DiscoveryV1EndpointPortType
from kubernetes_typed.client.models.v1_endpoint import V1EndpointType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1EndpointSliceType:
    addressType: str
    apiVersion: str
    endpoints: List[V1EndpointType]
    kind: str
    metadata: V1ObjectMetaType
    ports: List[DiscoveryV1EndpointPortType]
