# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EphemeralContainerType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_container_port import V1ContainerPortType
from kubernetes_typed.client.models.v1_container_resize_policy import V1ContainerResizePolicyType
from kubernetes_typed.client.models.v1_env_from_source import V1EnvFromSourceType
from kubernetes_typed.client.models.v1_env_var import V1EnvVarType
from kubernetes_typed.client.models.v1_lifecycle import V1LifecycleType
from kubernetes_typed.client.models.v1_probe import V1ProbeType
from kubernetes_typed.client.models.v1_resource_requirements import V1ResourceRequirementsType
from kubernetes_typed.client.models.v1_security_context import V1SecurityContextType
from kubernetes_typed.client.models.v1_volume_device import V1VolumeDeviceType
from kubernetes_typed.client.models.v1_volume_mount import V1VolumeMountType


@dataclass
class V1EphemeralContainerType:
    args: List[str]
    command: List[str]
    env: List[V1EnvVarType]
    envFrom: List[V1EnvFromSourceType]
    image: str
    imagePullPolicy: str
    lifecycle: V1LifecycleType
    livenessProbe: V1ProbeType
    name: str
    ports: List[V1ContainerPortType]
    readinessProbe: V1ProbeType
    resizePolicy: List[V1ContainerResizePolicyType]
    resources: V1ResourceRequirementsType
    restartPolicy: str
    securityContext: V1SecurityContextType
    startupProbe: V1ProbeType
    stdin: bool
    stdinOnce: bool
    targetContainerName: str
    terminationMessagePath: str
    terminationMessagePolicy: str
    tty: bool
    volumeDevices: List[V1VolumeDeviceType]
    volumeMounts: List[V1VolumeMountType]
    workingDir: str
