# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ExemptPriorityLevelConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ExemptPriorityLevelConfigurationType:
    lendablePercent: int
    nominalConcurrencyShares: int
