# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EphemeralContainerType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_env_var import V1EnvVarType
from .v1_env_from_source import V1EnvFromSourceType
from .v1_lifecycle import V1LifecycleType
from .v1_probe import V1ProbeType
from .v1_container_port import V1ContainerPortType
from .v1_container_resize_policy import V1ContainerResizePolicyType
from .v1_resource_requirements import V1ResourceRequirementsType
from .v1_security_context import V1SecurityContextType
from .v1_volume_device import V1VolumeDeviceType
from .v1_volume_mount import V1VolumeMountType


@dataclass
class V1EphemeralContainerType:
    args: List[str]
    command: List[str]
    env: List[V1EnvVarType]
    env_from: List[V1EnvFromSourceType]
    image: str
    image_pull_policy: str
    lifecycle: V1LifecycleType
    liveness_probe: V1ProbeType
    name: str
    ports: List[V1ContainerPortType]
    readiness_probe: V1ProbeType
    resize_policy: List[V1ContainerResizePolicyType]
    resources: V1ResourceRequirementsType
    restart_policy: str
    security_context: V1SecurityContextType
    startup_probe: V1ProbeType
    stdin: bool
    stdin_once: bool
    target_container_name: str
    termination_message_path: str
    termination_message_policy: str
    tty: bool
    volume_devices: List[V1VolumeDeviceType]
    volume_mounts: List[V1VolumeMountType]
    working_dir: str
