# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvFromSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_config_map_env_source import V1ConfigMapEnvSourceType
from .v1_secret_env_source import V1SecretEnvSourceType


@dataclass
class V1EnvFromSourceType:
    config_map_ref: V1ConfigMapEnvSourceType
    prefix: str
    secret_ref: V1SecretEnvSourceType
