# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EphemeralVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_persistent_volume_claim_template import V1PersistentVolumeClaimTemplateType


@dataclass
class V1EphemeralVolumeSourceType:
    volumeClaimTemplate: V1PersistentVolumeClaimTemplateType
