# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointHintsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_for_zone import V1ForZoneType


@dataclass
class V1EndpointHintsType:
    for_zones: List[V1ForZoneType]
