# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvVarType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_env_var_source import V1EnvVarSourceType


@dataclass
class V1EnvVarType:
    name: str
    value: str
    value_from: V1EnvVarSourceType
