# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointAddressType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_reference import V1ObjectReferenceType


@dataclass
class V1EndpointAddressType:
    hostname: str
    ip: str
    node_name: str
    target_ref: V1ObjectReferenceType
