# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ExecActionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1ExecActionType:
    command: List[str]
