# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvFromSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_config_map_env_source import V1ConfigMapEnvSourceType
from kubernetes_typed.client.models.v1_secret_env_source import V1SecretEnvSourceType


@dataclass
class V1EnvFromSourceType:
    configMapRef: V1ConfigMapEnvSourceType
    prefix: str
    secretRef: V1SecretEnvSourceType
