# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlexPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_secret_reference import V1SecretReferenceType


@dataclass
class V1FlexPersistentVolumeSourceType:
    driver: str
    fsType: str
    options: Dict[str, str]
    readOnly: bool
    secretRef: V1SecretReferenceType
