# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlockerVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1FlockerVolumeSourceType:
    dataset_name: str
    dataset_uuid: str
