# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlowSchemaListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_flow_schema import V1FlowSchemaType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1FlowSchemaListType:
    apiVersion: str
    items: List[V1FlowSchemaType]
    kind: str
    metadata: V1ListMetaType
