# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FCVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1FCVolumeSourceType:
    fsType: str
    lun: int
    readOnly: bool
    targetWWNs: List[str]
    wwids: List[str]
