# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlowSchemaType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_flow_schema_spec import V1FlowSchemaSpecType
from kubernetes_typed.client.models.v1_flow_schema_status import V1FlowSchemaStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1FlowSchemaType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1FlowSchemaSpecType
    status: V1FlowSchemaStatusType
