# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FieldSelectorRequirementType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1FieldSelectorRequirementType:
    key: str
    operator: str
    values: List[str]
