# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FieldSelectorAttributesType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_field_selector_requirement import V1FieldSelectorRequirementType


@dataclass
class V1FieldSelectorAttributesType:
    rawSelector: str
    requirements: List[V1FieldSelectorRequirementType]
