# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlowSchemaSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_flow_distinguisher_method import V1FlowDistinguisherMethodType
from .v1_priority_level_configuration_reference import V1PriorityLevelConfigurationReferenceType
from .v1_policy_rules_with_subjects import V1PolicyRulesWithSubjectsType


@dataclass
class V1FlowSchemaSpecType:
    distinguisher_method: V1FlowDistinguisherMethodType
    matching_precedence: int
    priority_level_configuration: V1PriorityLevelConfigurationReferenceType
    rules: List[V1PolicyRulesWithSubjectsType]
