# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlexVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1FlexVolumeSourceType:
    driver: str
    fsType: str
    options: Dict[str, str]
    readOnly: bool
    secretRef: V1LocalObjectReferenceType
