# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlowDistinguisherMethodType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1FlowDistinguisherMethodType:
    type: str
