# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlexPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict

from .v1_secret_reference import V1SecretReferenceType


@dataclass
class V1FlexPersistentVolumeSourceType:
    driver: str
    fs_type: str
    options: Dict[str, str]
    read_only: bool
    secret_ref: V1SecretReferenceType
