# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1FlowSchemaSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_flow_distinguisher_method import V1FlowDistinguisherMethodType
from kubernetes_typed.client.models.v1_policy_rules_with_subjects import V1PolicyRulesWithSubjectsType
from kubernetes_typed.client.models.v1_priority_level_configuration_reference import V1PriorityLevelConfigurationReferenceType


@dataclass
class V1FlowSchemaSpecType:
    distinguisherMethod: V1FlowDistinguisherMethodType
    matchingPrecedence: int
    priorityLevelConfiguration: V1PriorityLevelConfigurationReferenceType
    rules: List[V1PolicyRulesWithSubjectsType]
