# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GCEPersistentDiskVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1GCEPersistentDiskVolumeSourceType:
    fsType: str
    partition: int
    pdName: str
    readOnly: bool
