# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GCEPersistentDiskVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1GCEPersistentDiskVolumeSourceType:
    fs_type: str
    partition: int
    pd_name: str
    read_only: bool
