# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GRPCActionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1GRPCActionType:
    port: int
    service: str
