# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GroupVersionForDiscoveryType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1GroupVersionForDiscoveryType:
    group_version: str
    version: str
