# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GlusterfsVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1GlusterfsVolumeSourceType:
    endpoints: str
    path: str
    read_only: bool
