# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GlusterfsPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1GlusterfsPersistentVolumeSourceType:
    endpoints: str
    endpointsNamespace: str
    path: str
    readOnly: bool
