# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HostAliasType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1HostAliasType:
    hostnames: List[str]
    ip: str
