# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HTTPGetActionType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_http_header import V1HTTPHeaderType


@dataclass
class V1HTTPGetActionType:
    host: str
    httpHeaders: List[V1HTTPHeaderType]
    path: str
    port: object
    scheme: str
