# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HostPathVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1HostPathVolumeSourceType:
    path: str
    type: str
