# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_cross_version_object_reference import V1CrossVersionObjectReferenceType


@dataclass
class V1HorizontalPodAutoscalerSpecType:
    maxReplicas: int
    minReplicas: int
    scaleTargetRef: V1CrossVersionObjectReferenceType
    targetCPUUtilizationPercentage: int
