# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HTTPIngressPathType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_ingress_backend import V1IngressBackendType


@dataclass
class V1HTTPIngressPathType:
    backend: V1IngressBackendType
    path: str
    path_type: str
