# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_horizontal_pod_autoscaler_spec import V1HorizontalPodAutoscalerSpecType
from .v1_horizontal_pod_autoscaler_status import V1HorizontalPodAutoscalerStatusType


@dataclass
class V1HorizontalPodAutoscalerType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1HorizontalPodAutoscalerSpecType
    status: V1HorizontalPodAutoscalerStatusType
