# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_cross_version_object_reference import V1CrossVersionObjectReferenceType


@dataclass
class V1HorizontalPodAutoscalerSpecType:
    max_replicas: int
    min_replicas: int
    scale_target_ref: V1CrossVersionObjectReferenceType
    target_cpu_utilization_percentage: int
