# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_horizontal_pod_autoscaler import V1HorizontalPodAutoscalerType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1HorizontalPodAutoscalerListType:
    apiVersion: str
    items: List[V1HorizontalPodAutoscalerType]
    kind: str
    metadata: V1ListMetaType
