# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HTTPIngressRuleValueType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_http_ingress_path import V1HTTPIngressPathType


@dataclass
class V1HTTPIngressRuleValueType:
    paths: List[V1HTTPIngressPathType]
