# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1HorizontalPodAutoscalerStatusType:
    current_cpu_utilization_percentage: int
    current_replicas: int
    desired_replicas: int
    last_scale_time: datetime.datetime
    observed_generation: int
