# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1HorizontalPodAutoscalerStatusType:
    currentCPUUtilizationPercentage: int
    currentReplicas: int
    desiredReplicas: int
    lastScaleTime: datetime.datetime
    observedGeneration: int
