# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ISCSIVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1ISCSIVolumeSourceType:
    chapAuthDiscovery: bool
    chapAuthSession: bool
    fsType: str
    initiatorName: str
    iqn: str
    iscsiInterface: str
    lun: int
    portals: List[str]
    readOnly: bool
    secretRef: V1LocalObjectReferenceType
    targetPortal: str
