# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ISCSIPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_secret_reference import V1SecretReferenceType


@dataclass
class V1ISCSIPersistentVolumeSourceType:
    chap_auth_discovery: bool
    chap_auth_session: bool
    fs_type: str
    initiator_name: str
    iqn: str
    iscsi_interface: str
    lun: int
    portals: List[str]
    read_only: bool
    secret_ref: V1SecretReferenceType
    target_portal: str
