# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ISCSIVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1ISCSIVolumeSourceType:
    chap_auth_discovery: bool
    chap_auth_session: bool
    fs_type: str
    initiator_name: str
    iqn: str
    iscsi_interface: str
    lun: int
    portals: List[str]
    read_only: bool
    secret_ref: V1LocalObjectReferenceType
    target_portal: str
