# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_ingress import V1IngressType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1IngressListType:
    api_version: str
    items: List[V1IngressType]
    kind: str
    metadata: V1ListMetaType
