# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressTLSType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1IngressTLSType:
    hosts: List[str]
    secret_name: str
