# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_ingress_spec import V1IngressSpecType
from .v1_ingress_status import V1IngressStatusType


@dataclass
class V1IngressType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1IngressSpecType
    status: V1IngressStatusType
