# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_ingress_backend import V1IngressBackendType
from kubernetes_typed.client.models.v1_ingress_rule import V1IngressRuleType
from kubernetes_typed.client.models.v1_ingress_tls import V1IngressTLSType


@dataclass
class V1IngressSpecType:
    defaultBackend: V1IngressBackendType
    ingressClassName: str
    rules: List[V1IngressRuleType]
    tls: List[V1IngressTLSType]
