# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_http_ingress_rule_value import V1HTTPIngressRuleValueType


@dataclass
class V1IngressRuleType:
    host: str
    http: V1HTTPIngressRuleValueType
