# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressLoadBalancerIngressType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_ingress_port_status import V1IngressPortStatusType


@dataclass
class V1IngressLoadBalancerIngressType:
    hostname: str
    ip: str
    ports: List[V1IngressPortStatusType]
