# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ISCSIPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_secret_reference import V1SecretReferenceType


@dataclass
class V1ISCSIPersistentVolumeSourceType:
    chapAuthDiscovery: bool
    chapAuthSession: bool
    fsType: str
    initiatorName: str
    iqn: str
    iscsiInterface: str
    lun: int
    portals: List[str]
    readOnly: bool
    secretRef: V1SecretReferenceType
    targetPortal: str
