# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IPBlockType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass, field


@dataclass
class V1IPBlockType:
    cidr: str
    except_: List[str] = field(metadata={"alias": "except"})
