# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressPortStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1IngressPortStatusType:
    error: str
    port: int
    protocol: str
