# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_ingress_class_spec import V1IngressClassSpecType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1IngressClassType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1IngressClassSpecType
