# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_ingress_class import V1IngressClassType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1IngressClassListType:
    apiVersion: str
    items: List[V1IngressClassType]
    kind: str
    metadata: V1ListMetaType
