# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_ingress import V1IngressType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1IngressListType:
    apiVersion: str
    items: List[V1IngressType]
    kind: str
    metadata: V1ListMetaType
