# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_ingress_load_balancer_status import V1IngressLoadBalancerStatusType


@dataclass
class V1IngressStatusType:
    load_balancer: V1IngressLoadBalancerStatusType
