# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_ingress_class_parameters_reference import V1IngressClassParametersReferenceType


@dataclass
class V1IngressClassSpecType:
    controller: str
    parameters: V1IngressClassParametersReferenceType
