# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressLoadBalancerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_ingress_load_balancer_ingress import V1IngressLoadBalancerIngressType


@dataclass
class V1IngressLoadBalancerStatusType:
    ingress: List[V1IngressLoadBalancerIngressType]
