# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_ingress_class_spec import V1IngressClassSpecType


@dataclass
class V1IngressClassType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1IngressClassSpecType
