# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_ingress_backend import V1IngressBackendType
from .v1_ingress_rule import V1IngressRuleType
from .v1_ingress_tls import V1IngressTLSType


@dataclass
class V1IngressSpecType:
    default_backend: V1IngressBackendType
    ingress_class_name: str
    rules: List[V1IngressRuleType]
    tls: List[V1IngressTLSType]
