# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassParametersReferenceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1IngressClassParametersReferenceType:
    apiGroup: str
    kind: str
    name: str
    namespace: str
    scope: str
