# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JSONSchemaPropsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Any, Dict, List

from dataclasses import dataclass, field
from kubernetes_typed.client.models.v1_external_documentation import V1ExternalDocumentationType
from kubernetes_typed.client.models.v1_validation_rule import V1ValidationRuleType


@dataclass
class V1JSONSchemaPropsType:
    ref: str = field(metadata={"alias": "$ref"})
    schema: str = field(metadata={"alias": "$schema"})
    additionalItems: object
    additionalProperties: object
    allOf: List[Dict[Any, Any]]
    anyOf: List[Dict[Any, Any]]
    default: object
    definitions: Dict[str, Dict[Any, Any]]
    dependencies: Dict[str, object]
    description: str
    enum: List[object]
    example: object
    exclusiveMaximum: bool
    exclusiveMinimum: bool
    externalDocs: V1ExternalDocumentationType
    format: str
    id: str
    items: object
    maxItems: int
    maxLength: int
    maxProperties: int
    maximum: float
    minItems: int
    minLength: int
    minProperties: int
    minimum: float
    multipleOf: float
    not_: Dict[Any, Any] = field(metadata={"alias": "not"})
    nullable: bool
    oneOf: List[Dict[Any, Any]]
    pattern: str
    patternProperties: Dict[str, Dict[Any, Any]]
    properties: Dict[str, Dict[Any, Any]]
    required: List[str]
    title: str
    type: str
    uniqueItems: bool
    x_kubernetes_embedded_resource: bool = field(metadata={"alias": "x-kubernetes-embedded-resource"})
    x_kubernetes_int_or_string: bool = field(metadata={"alias": "x-kubernetes-int-or-string"})
    x_kubernetes_list_map_keys: List[str] = field(metadata={"alias": "x-kubernetes-list-map-keys"})
    x_kubernetes_list_type: str = field(metadata={"alias": "x-kubernetes-list-type"})
    x_kubernetes_map_type: str = field(metadata={"alias": "x-kubernetes-map-type"})
    x_kubernetes_preserve_unknown_fields: bool = field(metadata={"alias": "x-kubernetes-preserve-unknown-fields"})
    x_kubernetes_validations: List[V1ValidationRuleType] = field(metadata={"alias": "x-kubernetes-validations"})
