# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_job_spec import V1JobSpecType
from kubernetes_typed.client.models.v1_job_status import V1JobStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1JobType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1JobSpecType
    status: V1JobStatusType
