# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_pod_failure_policy import V1PodFailurePolicyType
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecType
from kubernetes_typed.client.models.v1_success_policy import V1SuccessPolicyType


@dataclass
class V1JobSpecType:
    activeDeadlineSeconds: int
    backoffLimit: int
    backoffLimitPerIndex: int
    completionMode: str
    completions: int
    managedBy: str
    manualSelector: bool
    maxFailedIndexes: int
    parallelism: int
    podFailurePolicy: V1PodFailurePolicyType
    podReplacementPolicy: str
    selector: V1LabelSelectorType
    successPolicy: V1SuccessPolicyType
    suspend: bool
    template: V1PodTemplateSpecType
    ttlSecondsAfterFinished: int
