# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_pod_failure_policy import V1PodFailurePolicyType
from .v1_label_selector import V1LabelSelectorType
from .v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1JobSpecType:
    active_deadline_seconds: int
    backoff_limit: int
    backoff_limit_per_index: int
    completion_mode: str
    completions: int
    manual_selector: bool
    max_failed_indexes: int
    parallelism: int
    pod_failure_policy: V1PodFailurePolicyType
    pod_replacement_policy: str
    selector: V1LabelSelectorType
    suspend: bool
    template: V1PodTemplateSpecType
    ttl_seconds_after_finished: int
