# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass
from typing import List

from .v1_job_condition import V1JobConditionType
from .v1_uncounted_terminated_pods import V1UncountedTerminatedPodsType


@dataclass
class V1JobStatusType:
    active: int
    completed_indexes: str
    completion_time: datetime.datetime
    conditions: List[V1JobConditionType]
    failed: int
    failed_indexes: str
    ready: int
    start_time: datetime.datetime
    succeeded: int
    terminating: int
    uncounted_terminated_pods: V1UncountedTerminatedPodsType
