# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobTemplateSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_job_spec import V1JobSpecType


@dataclass
class V1JobTemplateSpecType:
    metadata: V1ObjectMetaType
    spec: V1JobSpecType
