# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_job import V1JobType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1JobListType:
    apiVersion: str
    items: List[V1JobType]
    kind: str
    metadata: V1ListMetaType
