# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_job_condition import V1JobConditionType
from kubernetes_typed.client.models.v1_uncounted_terminated_pods import V1UncountedTerminatedPodsType


@dataclass
class V1JobStatusType:
    active: int
    completedIndexes: str
    completionTime: datetime.datetime
    conditions: List[V1JobConditionType]
    failed: int
    failedIndexes: str
    ready: int
    startTime: datetime.datetime
    succeeded: int
    terminating: int
    uncountedTerminatedPods: V1UncountedTerminatedPodsType
