# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JSONSchemaPropsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Any, Dict, List

from .v1_external_documentation import V1ExternalDocumentationType
from .v1_validation_rule import V1ValidationRuleType


@dataclass
class V1JSONSchemaPropsType:
    ref: str
    schema: str
    additional_items: object
    additional_properties: object
    all_of: List[Dict[Any, Any]]
    any_of: List[Dict[Any, Any]]
    default: object
    definitions: Dict[str, Dict[Any, Any]]
    dependencies: Dict[str, object]
    description: str
    enum: List[object]
    example: object
    exclusive_maximum: bool
    exclusive_minimum: bool
    external_docs: V1ExternalDocumentationType
    format: str
    id: str
    items: object
    max_items: int
    max_length: int
    max_properties: int
    maximum: float
    min_items: int
    min_length: int
    min_properties: int
    minimum: float
    multiple_of: float
    _not: Dict[Any, Any]
    nullable: bool
    one_of: List[Dict[Any, Any]]
    pattern: str
    pattern_properties: Dict[str, Dict[Any, Any]]
    properties: Dict[str, Dict[Any, Any]]
    required: List[str]
    title: str
    type: str
    unique_items: bool
    x_kubernetes_embedded_resource: bool
    x_kubernetes_int_or_string: bool
    x_kubernetes_list_map_keys: List[str]
    x_kubernetes_list_type: str
    x_kubernetes_map_type: str
    x_kubernetes_preserve_unknown_fields: bool
    x_kubernetes_validations: List[V1ValidationRuleType]
