# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1KeyToPathType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1KeyToPathType:
    key: str
    mode: int
    path: str
