# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeItemType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass


@dataclass
class V1LimitRangeItemType:
    default: Dict[str, str]
    defaultRequest: Dict[str, str]
    max: Dict[str, str]
    maxLimitRequestRatio: Dict[str, str]
    min: Dict[str, str]
    type: str
