# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LifecycleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_lifecycle_handler import V1LifecycleHandlerType


@dataclass
class V1LifecycleType:
    post_start: V1LifecycleHandlerType
    pre_stop: V1LifecycleHandlerType
