# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LinuxContainerUserType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1LinuxContainerUserType:
    gid: int
    supplementalGroups: List[int]
    uid: int
