# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LoadBalancerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_load_balancer_ingress import V1LoadBalancerIngressType


@dataclass
class V1LoadBalancerStatusType:
    ingress: List[V1LoadBalancerIngressType]
