# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitedPriorityLevelConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_limit_response import V1LimitResponseType


@dataclass
class V1LimitedPriorityLevelConfigurationType:
    borrowing_limit_percent: int
    lendable_percent: int
    limit_response: V1LimitResponseType
    nominal_concurrency_shares: int
