# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_limit_range_spec import V1LimitRangeSpecType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1LimitRangeType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1LimitRangeSpecType
