# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LabelSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector_requirement import V1LabelSelectorRequirementType


@dataclass
class V1LabelSelectorType:
    matchExpressions: List[V1LabelSelectorRequirementType]
    matchLabels: Dict[str, str]
