# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_limit_range_spec import V1LimitRangeSpecType


@dataclass
class V1LimitRangeType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1LimitRangeSpecType
