# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LeaseListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_lease import V1LeaseType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1LeaseListType:
    api_version: str
    items: List[V1LeaseType]
    kind: str
    metadata: V1ListMetaType
