# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LeaseSpecType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1LeaseSpecType:
    acquire_time: datetime.datetime
    holder_identity: str
    lease_duration_seconds: int
    lease_transitions: int
    renew_time: datetime.datetime
