# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LabelSelectorAttributesType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector_requirement import V1LabelSelectorRequirementType


@dataclass
class V1LabelSelectorAttributesType:
    rawSelector: str
    requirements: List[V1LabelSelectorRequirementType]
