# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ListMetaType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ListMetaType:
    _continue: str
    remaining_item_count: int
    resource_version: str
    self_link: str
