# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitedPriorityLevelConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_limit_response import V1LimitResponseType


@dataclass
class V1LimitedPriorityLevelConfigurationType:
    borrowingLimitPercent: int
    lendablePercent: int
    limitResponse: V1LimitResponseType
    nominalConcurrencyShares: int
