# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LoadBalancerIngressType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_port_status import V1PortStatusType


@dataclass
class V1LoadBalancerIngressType:
    hostname: str
    ip: str
    ip_mode: str
    ports: List[V1PortStatusType]
