# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LeaseListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_lease import V1LeaseType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1LeaseListType:
    apiVersion: str
    items: List[V1LeaseType]
    kind: str
    metadata: V1ListMetaType
