# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LifecycleType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_lifecycle_handler import V1LifecycleHandlerType


@dataclass
class V1LifecycleType:
    postStart: V1LifecycleHandlerType
    preStop: V1LifecycleHandlerType
