# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitResponseType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_queuing_configuration import V1QueuingConfigurationType


@dataclass
class V1LimitResponseType:
    queuing: V1QueuingConfigurationType
    type: str
