# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_limit_range_item import V1LimitRangeItemType


@dataclass
class V1LimitRangeSpecType:
    limits: List[V1LimitRangeItemType]
