# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LeaseType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_lease_spec import V1LeaseSpecType


@dataclass
class V1LeaseType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1LeaseSpecType
