# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LeaseSpecType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1LeaseSpecType:
    acquireTime: datetime.datetime
    holderIdentity: str
    leaseDurationSeconds: int
    leaseTransitions: int
    preferredHolder: str
    renewTime: datetime.datetime
    strategy: str
