# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LeaseType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_lease_spec import V1LeaseSpecType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1LeaseType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1LeaseSpecType
