# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_limit_range import V1LimitRangeType
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType


@dataclass
class V1LimitRangeListType:
    apiVersion: str
    items: List[V1LimitRangeType]
    kind: str
    metadata: V1ListMetaType
