# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ListMetaType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass, field


@dataclass
class V1ListMetaType:
    continue_: str = field(metadata={"alias": "continue"})
    remainingItemCount: int
    resourceVersion: str
    selfLink: str
