# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LifecycleHandlerType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_exec_action import V1ExecActionType
from .v1_http_get_action import V1HTTPGetActionType
from .v1_sleep_action import V1SleepActionType
from .v1_tcp_socket_action import V1TCPSocketActionType


@dataclass
class V1LifecycleHandlerType:
    _exec: V1ExecActionType
    http_get: V1HTTPGetActionType
    sleep: V1SleepActionType
    tcp_socket: V1TCPSocketActionType
