# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LocalVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1LocalVolumeSourceType:
    fs_type: str
    path: str
