# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeItemType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict


@dataclass
class V1LimitRangeItemType:
    default: Dict[str, str]
    default_request: Dict[str, str]
    max: Dict[str, str]
    max_limit_request_ratio: Dict[str, str]
    min: Dict[str, str]
    type: str
