# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LabelSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict, List

from .v1_label_selector_requirement import V1LabelSelectorRequirementType


@dataclass
class V1LabelSelectorType:
    match_expressions: List[V1LabelSelectorRequirementType]
    match_labels: Dict[str, str]
