# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LifecycleHandlerType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_exec_action import V1ExecActionType
from kubernetes_typed.client.models.v1_http_get_action import V1HTTPGetActionType
from kubernetes_typed.client.models.v1_sleep_action import V1SleepActionType
from kubernetes_typed.client.models.v1_tcp_socket_action import V1TCPSocketActionType


@dataclass
class V1LifecycleHandlerType:
    exec: V1ExecActionType
    httpGet: V1HTTPGetActionType
    sleep: V1SleepActionType
    tcpSocket: V1TCPSocketActionType
