# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LoadBalancerIngressType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_port_status import V1PortStatusType


@dataclass
class V1LoadBalancerIngressType:
    hostname: str
    ip: str
    ipMode: str
    ports: List[V1PortStatusType]
