# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ModifyVolumeStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ModifyVolumeStatusType:
    status: str
    target_volume_attributes_class_name: str
