# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1MutatingWebhookType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .admissionregistration_v1_webhook_client_config import AdmissionregistrationV1WebhookClientConfigType
from .v1_match_condition import V1MatchConditionType
from .v1_label_selector import V1LabelSelectorType
from .v1_rule_with_operations import V1RuleWithOperationsType


@dataclass
class V1MutatingWebhookType:
    admission_review_versions: List[str]
    client_config: AdmissionregistrationV1WebhookClientConfigType
    failure_policy: str
    match_conditions: List[V1MatchConditionType]
    match_policy: str
    name: str
    namespace_selector: V1LabelSelectorType
    object_selector: V1LabelSelectorType
    reinvocation_policy: str
    rules: List[V1RuleWithOperationsType]
    side_effects: str
    timeout_seconds: int
