# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1MutatingWebhookType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.admissionregistration_v1_webhook_client_config import AdmissionregistrationV1WebhookClientConfigType
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_match_condition import V1MatchConditionType
from kubernetes_typed.client.models.v1_rule_with_operations import V1RuleWithOperationsType


@dataclass
class V1MutatingWebhookType:
    admissionReviewVersions: List[str]
    clientConfig: AdmissionregistrationV1WebhookClientConfigType
    failurePolicy: str
    matchConditions: List[V1MatchConditionType]
    matchPolicy: str
    name: str
    namespaceSelector: V1LabelSelectorType
    objectSelector: V1LabelSelectorType
    reinvocationPolicy: str
    rules: List[V1RuleWithOperationsType]
    sideEffects: str
    timeoutSeconds: int
