# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ManagedFieldsEntryType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1ManagedFieldsEntryType:
    api_version: str
    fields_type: str
    fields_v1: object
    manager: str
    operation: str
    subresource: str
    time: datetime.datetime
