# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1MutatingWebhookConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_mutating_webhook_configuration import V1MutatingWebhookConfigurationType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1MutatingWebhookConfigurationListType:
    api_version: str
    items: List[V1MutatingWebhookConfigurationType]
    kind: str
    metadata: V1ListMetaType
