# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1MutatingWebhookConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_mutating_webhook_configuration import V1MutatingWebhookConfigurationType


@dataclass
class V1MutatingWebhookConfigurationListType:
    apiVersion: str
    items: List[V1MutatingWebhookConfigurationType]
    kind: str
    metadata: V1ListMetaType
