# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1MatchConditionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1MatchConditionType:
    expression: str
    name: str
