# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ManagedFieldsEntryType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1ManagedFieldsEntryType:
    apiVersion: str
    fieldsType: str
    fieldsV1: object
    manager: str
    operation: str
    subresource: str
    time: datetime.datetime
