# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1MutatingWebhookConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_mutating_webhook import V1MutatingWebhookType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1MutatingWebhookConfigurationType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    webhooks: List[V1MutatingWebhookType]
