# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1MatchResourcesType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_named_rule_with_operations import V1NamedRuleWithOperationsType


@dataclass
class V1MatchResourcesType:
    excludeResourceRules: List[V1NamedRuleWithOperationsType]
    matchPolicy: str
    namespaceSelector: V1LabelSelectorType
    objectSelector: V1LabelSelectorType
    resourceRules: List[V1NamedRuleWithOperationsType]
