# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NonResourceAttributesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1NonResourceAttributesType:
    path: str
    verb: str
