# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_namespace_spec import V1NamespaceSpecType
from kubernetes_typed.client.models.v1_namespace_status import V1NamespaceStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1NamespaceType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1NamespaceSpecType
    status: V1NamespaceStatusType
