# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeRuntimeHandlerFeaturesType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1NodeRuntimeHandlerFeaturesType:
    recursiveReadOnlyMounts: bool
    userNamespaces: bool
