# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_selector_term import V1NodeSelectorTermType


@dataclass
class V1NodeSelectorType:
    nodeSelectorTerms: List[V1NodeSelectorTermType]
