# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyPeerType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_ip_block import V1IPBlockType
from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1NetworkPolicyPeerType:
    ip_block: V1IPBlockType
    namespace_selector: V1LabelSelectorType
    pod_selector: V1LabelSelectorType
