# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1NamespaceSpecType:
    finalizers: List[str]
