# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeAffinityType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_selector import V1NodeSelectorType
from kubernetes_typed.client.models.v1_preferred_scheduling_term import V1PreferredSchedulingTermType


@dataclass
class V1NodeAffinityType:
    preferredDuringSchedulingIgnoredDuringExecution: List[V1PreferredSchedulingTermType]
    requiredDuringSchedulingIgnoredDuringExecution: V1NodeSelectorType
