# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeRuntimeHandlerType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_runtime_handler_features import V1NodeRuntimeHandlerFeaturesType


@dataclass
class V1NodeRuntimeHandlerType:
    features: V1NodeRuntimeHandlerFeaturesType
    name: str
