# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_network_policy_spec import V1NetworkPolicySpecType


@dataclass
class V1NetworkPolicyType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1NetworkPolicySpecType
