# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_attached_volume import V1AttachedVolumeType
from kubernetes_typed.client.models.v1_container_image import V1ContainerImageType
from kubernetes_typed.client.models.v1_node_address import V1NodeAddressType
from kubernetes_typed.client.models.v1_node_condition import V1NodeConditionType
from kubernetes_typed.client.models.v1_node_config_status import V1NodeConfigStatusType
from kubernetes_typed.client.models.v1_node_daemon_endpoints import V1NodeDaemonEndpointsType
from kubernetes_typed.client.models.v1_node_features import V1NodeFeaturesType
from kubernetes_typed.client.models.v1_node_runtime_handler import V1NodeRuntimeHandlerType
from kubernetes_typed.client.models.v1_node_system_info import V1NodeSystemInfoType


@dataclass
class V1NodeStatusType:
    addresses: List[V1NodeAddressType]
    allocatable: Dict[str, str]
    capacity: Dict[str, str]
    conditions: List[V1NodeConditionType]
    config: V1NodeConfigStatusType
    daemonEndpoints: V1NodeDaemonEndpointsType
    features: V1NodeFeaturesType
    images: List[V1ContainerImageType]
    nodeInfo: V1NodeSystemInfoType
    phase: str
    runtimeHandlers: List[V1NodeRuntimeHandlerType]
    volumesAttached: List[V1AttachedVolumeType]
    volumesInUse: List[str]
