# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyPeerType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_ip_block import V1IPBlockType
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType


@dataclass
class V1NetworkPolicyPeerType:
    ipBlock: V1IPBlockType
    namespaceSelector: V1LabelSelectorType
    podSelector: V1LabelSelectorType
