# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeConfigSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_config_map_node_config_source import V1ConfigMapNodeConfigSourceType


@dataclass
class V1NodeConfigSourceType:
    configMap: V1ConfigMapNodeConfigSourceType
