# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_network_policy import V1NetworkPolicyType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1NetworkPolicyListType:
    api_version: str
    items: List[V1NetworkPolicyType]
    kind: str
    metadata: V1ListMetaType
