# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicySpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_network_policy_egress_rule import V1NetworkPolicyEgressRuleType
from kubernetes_typed.client.models.v1_network_policy_ingress_rule import V1NetworkPolicyIngressRuleType


@dataclass
class V1NetworkPolicySpecType:
    egress: List[V1NetworkPolicyEgressRuleType]
    ingress: List[V1NetworkPolicyIngressRuleType]
    podSelector: V1LabelSelectorType
    policyTypes: List[str]
