# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeAffinityType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_preferred_scheduling_term import V1PreferredSchedulingTermType
from .v1_node_selector import V1NodeSelectorType


@dataclass
class V1NodeAffinityType:
    preferred_during_scheduling_ignored_during_execution: List[V1PreferredSchedulingTermType]
    required_during_scheduling_ignored_during_execution: V1NodeSelectorType
