# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_config_source import V1NodeConfigSourceType
from kubernetes_typed.client.models.v1_taint import V1TaintType


@dataclass
class V1NodeSpecType:
    configSource: V1NodeConfigSourceType
    externalID: str
    podCIDR: str
    podCIDRs: List[str]
    providerID: str
    taints: List[V1TaintType]
    unschedulable: bool
