# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeConfigStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_node_config_source import V1NodeConfigSourceType


@dataclass
class V1NodeConfigStatusType:
    active: V1NodeConfigSourceType
    assigned: V1NodeConfigSourceType
    error: str
    last_known_good: V1NodeConfigSourceType
