# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_spec import V1NodeSpecType
from kubernetes_typed.client.models.v1_node_status import V1NodeStatusType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1NodeType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1NodeSpecType
    status: V1NodeStatusType
