# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicySpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_network_policy_egress_rule import V1NetworkPolicyEgressRuleType
from .v1_network_policy_ingress_rule import V1NetworkPolicyIngressRuleType
from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1NetworkPolicySpecType:
    egress: List[V1NetworkPolicyEgressRuleType]
    ingress: List[V1NetworkPolicyIngressRuleType]
    pod_selector: V1LabelSelectorType
    policy_types: List[str]
