# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_namespace_condition import V1NamespaceConditionType


@dataclass
class V1NamespaceStatusType:
    conditions: List[V1NamespaceConditionType]
    phase: str
