# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_namespace import V1NamespaceType


@dataclass
class V1NamespaceListType:
    apiVersion: str
    items: List[V1NamespaceType]
    kind: str
    metadata: V1ListMetaType
