# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_namespace_spec import V1NamespaceSpecType
from .v1_namespace_status import V1NamespaceStatusType


@dataclass
class V1NamespaceType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1NamespaceSpecType
    status: V1NamespaceStatusType
