# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_node import V1NodeType


@dataclass
class V1NodeListType:
    apiVersion: str
    items: List[V1NodeType]
    kind: str
    metadata: V1ListMetaType
