# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSelectorTermType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_selector_requirement import V1NodeSelectorRequirementType


@dataclass
class V1NodeSelectorTermType:
    matchExpressions: List[V1NodeSelectorRequirementType]
    matchFields: List[V1NodeSelectorRequirementType]
