# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_network_policy import V1NetworkPolicyType


@dataclass
class V1NetworkPolicyListType:
    apiVersion: str
    items: List[V1NetworkPolicyType]
    kind: str
    metadata: V1ListMetaType
