# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyEgressRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_network_policy_port import V1NetworkPolicyPortType
from .v1_network_policy_peer import V1NetworkPolicyPeerType


@dataclass
class V1NetworkPolicyEgressRuleType:
    ports: List[V1NetworkPolicyPortType]
    to: List[V1NetworkPolicyPeerType]
