# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSelectorRequirementType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1NodeSelectorRequirementType:
    key: str
    operator: str
    values: List[str]
