# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_network_policy_spec import V1NetworkPolicySpecType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1NetworkPolicyType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1NetworkPolicySpecType
