# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeAddressType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1NodeAddressType:
    address: str
    type: str
