# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyIngressRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass, field
from kubernetes_typed.client.models.v1_network_policy_peer import V1NetworkPolicyPeerType
from kubernetes_typed.client.models.v1_network_policy_port import V1NetworkPolicyPortType


@dataclass
class V1NetworkPolicyIngressRuleType:
    from_: List[V1NetworkPolicyPeerType] = field(metadata={"alias": "from"})
    ports: List[V1NetworkPolicyPortType]
