# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NonResourceRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1NonResourceRuleType:
    nonResourceURLs: List[str]
    verbs: List[str]
