# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_node_spec import V1NodeSpecType
from .v1_node_status import V1NodeStatusType


@dataclass
class V1NodeType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1NodeSpecType
    status: V1NodeStatusType
