# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NonResourcePolicyRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1NonResourcePolicyRuleType:
    non_resource_ur_ls: List[str]
    verbs: List[str]
