# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_node_config_source import V1NodeConfigSourceType
from .v1_taint import V1TaintType


@dataclass
class V1NodeSpecType:
    config_source: V1NodeConfigSourceType
    external_id: str
    pod_cidr: str
    pod_cid_rs: List[str]
    provider_id: str
    taints: List[V1TaintType]
    unschedulable: bool
