# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NFSVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1NFSVolumeSourceType:
    path: str
    read_only: bool
    server: str
