# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_node_selector_term import V1NodeSelectorTermType


@dataclass
class V1NodeSelectorType:
    node_selector_terms: List[V1NodeSelectorTermType]
