# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyIngressRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_network_policy_peer import V1NetworkPolicyPeerType
from .v1_network_policy_port import V1NetworkPolicyPortType


@dataclass
class V1NetworkPolicyIngressRuleType:
    _from: List[V1NetworkPolicyPeerType]
    ports: List[V1NetworkPolicyPortType]
