# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ObjectMetaType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass
from typing import Dict, List

from .v1_managed_fields_entry import V1ManagedFieldsEntryType
from .v1_owner_reference import V1OwnerReferenceType


@dataclass
class V1ObjectMetaType:
    annotations: Dict[str, str]
    creation_timestamp: datetime.datetime
    deletion_grace_period_seconds: int
    deletion_timestamp: datetime.datetime
    finalizers: List[str]
    generate_name: str
    generation: int
    labels: Dict[str, str]
    managed_fields: List[V1ManagedFieldsEntryType]
    name: str
    namespace: str
    owner_references: List[V1OwnerReferenceType]
    resource_version: str
    self_link: str
    uid: str
