# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ObjectReferenceType:
    api_version: str
    field_path: str
    kind: str
    name: str
    namespace: str
    resource_version: str
    uid: str
