# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ObjectFieldSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ObjectFieldSelectorType:
    api_version: str
    field_path: str
