# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1OverheadType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass


@dataclass
class V1OverheadType:
    podFixed: Dict[str, str]
