# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ObjectReferenceType:
    apiVersion: str
    fieldPath: str
    kind: str
    name: str
    namespace: str
    resourceVersion: str
    uid: str
