# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ObjectMetaType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_managed_fields_entry import V1ManagedFieldsEntryType
from kubernetes_typed.client.models.v1_owner_reference import V1OwnerReferenceType


@dataclass
class V1ObjectMetaType:
    annotations: Dict[str, str]
    creationTimestamp: datetime.datetime
    deletionGracePeriodSeconds: int
    deletionTimestamp: datetime.datetime
    finalizers: List[str]
    generateName: str
    generation: int
    labels: Dict[str, str]
    managedFields: List[V1ManagedFieldsEntryType]
    name: str
    namespace: str
    ownerReferences: List[V1OwnerReferenceType]
    resourceVersion: str
    selfLink: str
    uid: str
