# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1OwnerReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1OwnerReferenceType:
    api_version: str
    block_owner_deletion: bool
    controller: bool
    kind: str
    name: str
    uid: str
