# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1OverheadType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict


@dataclass
class V1OverheadType:
    pod_fixed: Dict[str, str]
