# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PortworxVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1PortworxVolumeSourceType:
    fsType: str
    readOnly: bool
    volumeID: str
