# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_aws_elastic_block_store_volume_source import V1AWSElasticBlockStoreVolumeSourceType
from kubernetes_typed.client.models.v1_azure_disk_volume_source import V1AzureDiskVolumeSourceType
from kubernetes_typed.client.models.v1_azure_file_persistent_volume_source import V1AzureFilePersistentVolumeSourceType
from kubernetes_typed.client.models.v1_ceph_fs_persistent_volume_source import V1CephFSPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_cinder_persistent_volume_source import V1CinderPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_csi_persistent_volume_source import V1CSIPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_fc_volume_source import V1FCVolumeSourceType
from kubernetes_typed.client.models.v1_flex_persistent_volume_source import V1FlexPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_flocker_volume_source import V1FlockerVolumeSourceType
from kubernetes_typed.client.models.v1_gce_persistent_disk_volume_source import V1GCEPersistentDiskVolumeSourceType
from kubernetes_typed.client.models.v1_glusterfs_persistent_volume_source import V1GlusterfsPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_host_path_volume_source import V1HostPathVolumeSourceType
from kubernetes_typed.client.models.v1_iscsi_persistent_volume_source import V1ISCSIPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_local_volume_source import V1LocalVolumeSourceType
from kubernetes_typed.client.models.v1_nfs_volume_source import V1NFSVolumeSourceType
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType
from kubernetes_typed.client.models.v1_photon_persistent_disk_volume_source import V1PhotonPersistentDiskVolumeSourceType
from kubernetes_typed.client.models.v1_portworx_volume_source import V1PortworxVolumeSourceType
from kubernetes_typed.client.models.v1_quobyte_volume_source import V1QuobyteVolumeSourceType
from kubernetes_typed.client.models.v1_rbd_persistent_volume_source import V1RBDPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_scale_io_persistent_volume_source import V1ScaleIOPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_storage_os_persistent_volume_source import V1StorageOSPersistentVolumeSourceType
from kubernetes_typed.client.models.v1_volume_node_affinity import V1VolumeNodeAffinityType
from kubernetes_typed.client.models.v1_vsphere_virtual_disk_volume_source import V1VsphereVirtualDiskVolumeSourceType


@dataclass
class V1PersistentVolumeSpecType:
    accessModes: List[str]
    awsElasticBlockStore: V1AWSElasticBlockStoreVolumeSourceType
    azureDisk: V1AzureDiskVolumeSourceType
    azureFile: V1AzureFilePersistentVolumeSourceType
    capacity: Dict[str, str]
    cephfs: V1CephFSPersistentVolumeSourceType
    cinder: V1CinderPersistentVolumeSourceType
    claimRef: V1ObjectReferenceType
    csi: V1CSIPersistentVolumeSourceType
    fc: V1FCVolumeSourceType
    flexVolume: V1FlexPersistentVolumeSourceType
    flocker: V1FlockerVolumeSourceType
    gcePersistentDisk: V1GCEPersistentDiskVolumeSourceType
    glusterfs: V1GlusterfsPersistentVolumeSourceType
    hostPath: V1HostPathVolumeSourceType
    iscsi: V1ISCSIPersistentVolumeSourceType
    local: V1LocalVolumeSourceType
    mountOptions: List[str]
    nfs: V1NFSVolumeSourceType
    nodeAffinity: V1VolumeNodeAffinityType
    persistentVolumeReclaimPolicy: str
    photonPersistentDisk: V1PhotonPersistentDiskVolumeSourceType
    portworxVolume: V1PortworxVolumeSourceType
    quobyte: V1QuobyteVolumeSourceType
    rbd: V1RBDPersistentVolumeSourceType
    scaleIO: V1ScaleIOPersistentVolumeSourceType
    storageClassName: str
    storageos: V1StorageOSPersistentVolumeSourceType
    volumeAttributesClassName: str
    volumeMode: str
    vsphereVolume: V1VsphereVirtualDiskVolumeSourceType
