# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_persistent_volume_claim import V1PersistentVolumeClaimType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1PersistentVolumeClaimListType:
    api_version: str
    items: List[V1PersistentVolumeClaimType]
    kind: str
    metadata: V1ListMetaType
