# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodFailurePolicyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_pod_failure_policy_rule import V1PodFailurePolicyRuleType


@dataclass
class V1PodFailurePolicyType:
    rules: List[V1PodFailurePolicyRuleType]
