# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityLevelConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_priority_level_configuration_spec import V1PriorityLevelConfigurationSpecType
from kubernetes_typed.client.models.v1_priority_level_configuration_status import V1PriorityLevelConfigurationStatusType


@dataclass
class V1PriorityLevelConfigurationType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1PriorityLevelConfigurationSpecType
    status: V1PriorityLevelConfigurationStatusType
