# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDNSConfigOptionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PodDNSConfigOptionType:
    name: str
    value: str
