# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PhotonPersistentDiskVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PhotonPersistentDiskVolumeSourceType:
    fs_type: str
    pd_id: str
