# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_affinity import V1AffinityType
from kubernetes_typed.client.models.v1_container import V1ContainerType
from kubernetes_typed.client.models.v1_ephemeral_container import V1EphemeralContainerType
from kubernetes_typed.client.models.v1_host_alias import V1HostAliasType
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType
from kubernetes_typed.client.models.v1_pod_dns_config import V1PodDNSConfigType
from kubernetes_typed.client.models.v1_pod_os import V1PodOSType
from kubernetes_typed.client.models.v1_pod_readiness_gate import V1PodReadinessGateType
from kubernetes_typed.client.models.v1_pod_resource_claim import V1PodResourceClaimType
from kubernetes_typed.client.models.v1_pod_scheduling_gate import V1PodSchedulingGateType
from kubernetes_typed.client.models.v1_pod_security_context import V1PodSecurityContextType
from kubernetes_typed.client.models.v1_toleration import V1TolerationType
from kubernetes_typed.client.models.v1_topology_spread_constraint import V1TopologySpreadConstraintType
from kubernetes_typed.client.models.v1_volume import V1VolumeType


@dataclass
class V1PodSpecType:
    activeDeadlineSeconds: int
    affinity: V1AffinityType
    automountServiceAccountToken: bool
    containers: List[V1ContainerType]
    dnsConfig: V1PodDNSConfigType
    dnsPolicy: str
    enableServiceLinks: bool
    ephemeralContainers: List[V1EphemeralContainerType]
    hostAliases: List[V1HostAliasType]
    hostIPC: bool
    hostNetwork: bool
    hostPID: bool
    hostUsers: bool
    hostname: str
    imagePullSecrets: List[V1LocalObjectReferenceType]
    initContainers: List[V1ContainerType]
    nodeName: str
    nodeSelector: Dict[str, str]
    os: V1PodOSType
    overhead: Dict[str, str]
    preemptionPolicy: str
    priority: int
    priorityClassName: str
    readinessGates: List[V1PodReadinessGateType]
    resourceClaims: List[V1PodResourceClaimType]
    restartPolicy: str
    runtimeClassName: str
    schedulerName: str
    schedulingGates: List[V1PodSchedulingGateType]
    securityContext: V1PodSecurityContextType
    serviceAccount: str
    serviceAccountName: str
    setHostnameAsFQDN: bool
    shareProcessNamespace: bool
    subdomain: str
    terminationGracePeriodSeconds: int
    tolerations: List[V1TolerationType]
    topologySpreadConstraints: List[V1TopologySpreadConstraintType]
    volumes: List[V1VolumeType]
