# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityLevelConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_priority_level_configuration import V1PriorityLevelConfigurationType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1PriorityLevelConfigurationListType:
    api_version: str
    items: List[V1PriorityLevelConfigurationType]
    kind: str
    metadata: V1ListMetaType
