# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_container_status import V1ContainerStatusType
from kubernetes_typed.client.models.v1_host_ip import V1HostIPType
from kubernetes_typed.client.models.v1_pod_condition import V1PodConditionType
from kubernetes_typed.client.models.v1_pod_ip import V1PodIPType
from kubernetes_typed.client.models.v1_pod_resource_claim_status import V1PodResourceClaimStatusType


@dataclass
class V1PodStatusType:
    conditions: List[V1PodConditionType]
    containerStatuses: List[V1ContainerStatusType]
    ephemeralContainerStatuses: List[V1ContainerStatusType]
    hostIP: str
    hostIPs: List[V1HostIPType]
    initContainerStatuses: List[V1ContainerStatusType]
    message: str
    nominatedNodeName: str
    phase: str
    podIP: str
    podIPs: List[V1PodIPType]
    qosClass: str
    reason: str
    resize: str
    resourceClaimStatuses: List[V1PodResourceClaimStatusType]
    startTime: datetime.datetime
