# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityLevelConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_priority_level_configuration import V1PriorityLevelConfigurationType


@dataclass
class V1PriorityLevelConfigurationListType:
    apiVersion: str
    items: List[V1PriorityLevelConfigurationType]
    kind: str
    metadata: V1ListMetaType
