# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodResourceClaimType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_claim_source import V1ClaimSourceType


@dataclass
class V1PodResourceClaimType:
    name: str
    source: V1ClaimSourceType
