# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_modify_volume_status import V1ModifyVolumeStatusType
from kubernetes_typed.client.models.v1_persistent_volume_claim_condition import V1PersistentVolumeClaimConditionType


@dataclass
class V1PersistentVolumeClaimStatusType:
    accessModes: List[str]
    allocatedResourceStatuses: Dict[str, str]
    allocatedResources: Dict[str, str]
    capacity: Dict[str, str]
    conditions: List[V1PersistentVolumeClaimConditionType]
    currentVolumeAttributesClassName: str
    modifyVolumeStatus: V1ModifyVolumeStatusType
    phase: str
