# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ProbeType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_exec_action import V1ExecActionType
from kubernetes_typed.client.models.v1_grpc_action import V1GRPCActionType
from kubernetes_typed.client.models.v1_http_get_action import V1HTTPGetActionType
from kubernetes_typed.client.models.v1_tcp_socket_action import V1TCPSocketActionType


@dataclass
class V1ProbeType:
    exec: V1ExecActionType
    failureThreshold: int
    grpc: V1GRPCActionType
    httpGet: V1HTTPGetActionType
    initialDelaySeconds: int
    periodSeconds: int
    successThreshold: int
    tcpSocket: V1TCPSocketActionType
    terminationGracePeriodSeconds: int
    timeoutSeconds: int
