# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodTemplateType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1PodTemplateType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    template: V1PodTemplateSpecType
