# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_persistent_volume_claim_spec import V1PersistentVolumeClaimSpecType
from .v1_persistent_volume_claim_status import V1PersistentVolumeClaimStatusType


@dataclass
class V1PersistentVolumeClaimType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1PersistentVolumeClaimSpecType
    status: V1PersistentVolumeClaimStatusType
