# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_persistent_volume import V1PersistentVolumeType


@dataclass
class V1PersistentVolumeListType:
    apiVersion: str
    items: List[V1PersistentVolumeType]
    kind: str
    metadata: V1ListMetaType
