# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodTemplateListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_pod_template import V1PodTemplateType


@dataclass
class V1PodTemplateListType:
    apiVersion: str
    items: List[V1PodTemplateType]
    kind: str
    metadata: V1ListMetaType
