# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodFailurePolicyRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_pod_failure_policy_on_exit_codes_requirement import V1PodFailurePolicyOnExitCodesRequirementType
from kubernetes_typed.client.models.v1_pod_failure_policy_on_pod_conditions_pattern import V1PodFailurePolicyOnPodConditionsPatternType


@dataclass
class V1PodFailurePolicyRuleType:
    action: str
    onExitCodes: V1PodFailurePolicyOnExitCodesRequirementType
    onPodConditions: List[V1PodFailurePolicyOnPodConditionsPatternType]
