# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodAffinityType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_weighted_pod_affinity_term import V1WeightedPodAffinityTermType
from .v1_pod_affinity_term import V1PodAffinityTermType


@dataclass
class V1PodAffinityType:
    preferred_during_scheduling_ignored_during_execution: List[V1WeightedPodAffinityTermType]
    required_during_scheduling_ignored_during_execution: List[V1PodAffinityTermType]
