# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodSecurityContextType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_se_linux_options import V1SELinuxOptionsType
from .v1_seccomp_profile import V1SeccompProfileType
from .v1_sysctl import V1SysctlType
from .v1_windows_security_context_options import V1WindowsSecurityContextOptionsType


@dataclass
class V1PodSecurityContextType:
    fs_group: int
    fs_group_change_policy: str
    run_as_group: int
    run_as_non_root: bool
    run_as_user: int
    se_linux_options: V1SELinuxOptionsType
    seccomp_profile: V1SeccompProfileType
    supplemental_groups: List[int]
    sysctls: List[V1SysctlType]
    windows_options: V1WindowsSecurityContextOptionsType
