# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_typed_local_object_reference import V1TypedLocalObjectReferenceType
from kubernetes_typed.client.models.v1_typed_object_reference import V1TypedObjectReferenceType
from kubernetes_typed.client.models.v1_volume_resource_requirements import V1VolumeResourceRequirementsType


@dataclass
class V1PersistentVolumeClaimSpecType:
    accessModes: List[str]
    dataSource: V1TypedLocalObjectReferenceType
    dataSourceRef: V1TypedObjectReferenceType
    resources: V1VolumeResourceRequirementsType
    selector: V1LabelSelectorType
    storageClassName: str
    volumeAttributesClassName: str
    volumeMode: str
    volumeName: str
