# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ProjectedVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_volume_projection import V1VolumeProjectionType


@dataclass
class V1ProjectedVolumeSourceType:
    default_mode: int
    sources: List[V1VolumeProjectionType]
