# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType


@dataclass
class V1PodDisruptionBudgetSpecType:
    maxUnavailable: object
    minAvailable: object
    selector: V1LabelSelectorType
    unhealthyPodEvictionPolicy: str
