# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass
from typing import Dict, List

from .v1_condition import V1ConditionType


@dataclass
class V1PodDisruptionBudgetStatusType:
    conditions: List[V1ConditionType]
    current_healthy: int
    desired_healthy: int
    disrupted_pods: Dict[str, datetime.datetime]
    disruptions_allowed: int
    expected_pods: int
    observed_generation: int
