# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodResourceClaimStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PodResourceClaimStatusType:
    name: str
    resource_claim_name: str
