# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodTemplateListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_pod_template import V1PodTemplateType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1PodTemplateListType:
    api_version: str
    items: List[V1PodTemplateType]
    kind: str
    metadata: V1ListMetaType
