# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimConditionType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1PersistentVolumeClaimConditionType:
    lastProbeTime: datetime.datetime
    lastTransitionTime: datetime.datetime
    message: str
    reason: str
    status: str
    type: str
