# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodAntiAffinityType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_pod_affinity_term import V1PodAffinityTermType
from kubernetes_typed.client.models.v1_weighted_pod_affinity_term import V1WeightedPodAffinityTermType


@dataclass
class V1PodAntiAffinityType:
    preferredDuringSchedulingIgnoredDuringExecution: List[V1WeightedPodAffinityTermType]
    requiredDuringSchedulingIgnoredDuringExecution: List[V1PodAffinityTermType]
