# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PersistentVolumeClaimVolumeSourceType:
    claim_name: str
    read_only: bool
