# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict, List

from .v1_persistent_volume_claim_condition import V1PersistentVolumeClaimConditionType
from .v1_modify_volume_status import V1ModifyVolumeStatusType


@dataclass
class V1PersistentVolumeClaimStatusType:
    access_modes: List[str]
    allocated_resource_statuses: Dict[str, str]
    allocated_resources: Dict[str, str]
    capacity: Dict[str, str]
    conditions: List[V1PersistentVolumeClaimConditionType]
    current_volume_attributes_class_name: str
    modify_volume_status: V1ModifyVolumeStatusType
    phase: str
