# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PolicyRulesWithSubjectsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.flowcontrol_v1_subject import FlowcontrolV1SubjectType
from kubernetes_typed.client.models.v1_non_resource_policy_rule import V1NonResourcePolicyRuleType
from kubernetes_typed.client.models.v1_resource_policy_rule import V1ResourcePolicyRuleType


@dataclass
class V1PolicyRulesWithSubjectsType:
    nonResourceRules: List[V1NonResourcePolicyRuleType]
    resourceRules: List[V1ResourcePolicyRuleType]
    subjects: List[FlowcontrolV1SubjectType]
