# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityLevelConfigurationSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_exempt_priority_level_configuration import V1ExemptPriorityLevelConfigurationType
from .v1_limited_priority_level_configuration import V1LimitedPriorityLevelConfigurationType


@dataclass
class V1PriorityLevelConfigurationSpecType:
    exempt: V1ExemptPriorityLevelConfigurationType
    limited: V1LimitedPriorityLevelConfigurationType
    type: str
