# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_pod import V1PodType


@dataclass
class V1PodListType:
    apiVersion: str
    items: List[V1PodType]
    kind: str
    metadata: V1ListMetaType
