# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodSecurityContextType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_app_armor_profile import V1AppArmorProfileType
from kubernetes_typed.client.models.v1_se_linux_options import V1SELinuxOptionsType
from kubernetes_typed.client.models.v1_seccomp_profile import V1SeccompProfileType
from kubernetes_typed.client.models.v1_sysctl import V1SysctlType
from kubernetes_typed.client.models.v1_windows_security_context_options import V1WindowsSecurityContextOptionsType


@dataclass
class V1PodSecurityContextType:
    appArmorProfile: V1AppArmorProfileType
    fsGroup: int
    fsGroupChangePolicy: str
    runAsGroup: int
    runAsNonRoot: bool
    runAsUser: int
    seLinuxOptions: V1SELinuxOptionsType
    seccompProfile: V1SeccompProfileType
    supplementalGroups: List[int]
    supplementalGroupsPolicy: str
    sysctls: List[V1SysctlType]
    windowsOptions: V1WindowsSecurityContextOptionsType
