# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ProjectedVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_volume_projection import V1VolumeProjectionType


@dataclass
class V1ProjectedVolumeSourceType:
    defaultMode: int
    sources: List[V1VolumeProjectionType]
