# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1PersistentVolumeStatusType:
    last_phase_transition_time: datetime.datetime
    message: str
    phase: str
    reason: str
