# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PreconditionsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PreconditionsType:
    resource_version: str
    uid: str
