# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_pod_disruption_budget import V1PodDisruptionBudgetType


@dataclass
class V1PodDisruptionBudgetListType:
    apiVersion: str
    items: List[V1PodDisruptionBudgetType]
    kind: str
    metadata: V1ListMetaType
