# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PortworxVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PortworxVolumeSourceType:
    fs_type: str
    read_only: bool
    volume_id: str
