# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodAffinityTermType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1PodAffinityTermType:
    label_selector: V1LabelSelectorType
    match_label_keys: List[str]
    mismatch_label_keys: List[str]
    namespace_selector: V1LabelSelectorType
    namespaces: List[str]
    topology_key: str
