# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ProbeType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_exec_action import V1ExecActionType
from .v1_grpc_action import V1GRPCActionType
from .v1_http_get_action import V1HTTPGetActionType
from .v1_tcp_socket_action import V1TCPSocketActionType


@dataclass
class V1ProbeType:
    _exec: V1ExecActionType
    failure_threshold: int
    grpc: V1GRPCActionType
    http_get: V1HTTPGetActionType
    initial_delay_seconds: int
    period_seconds: int
    success_threshold: int
    tcp_socket: V1TCPSocketActionType
    termination_grace_period_seconds: int
    timeout_seconds: int
