# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodAffinityTermType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType


@dataclass
class V1PodAffinityTermType:
    labelSelector: V1LabelSelectorType
    matchLabelKeys: List[str]
    mismatchLabelKeys: List[str]
    namespaceSelector: V1LabelSelectorType
    namespaces: List[str]
    topologyKey: str
