# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_condition import V1ConditionType


@dataclass
class V1PodDisruptionBudgetStatusType:
    conditions: List[V1ConditionType]
    currentHealthy: int
    desiredHealthy: int
    disruptedPods: Dict[str, datetime.datetime]
    disruptionsAllowed: int
    expectedPods: int
    observedGeneration: int
