# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodIPType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PodIPType:
    ip: str
