# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodFailurePolicyOnExitCodesRequirementType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1PodFailurePolicyOnExitCodesRequirementType:
    containerName: str
    operator: str
    values: List[int]
