# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_priority_class import V1PriorityClassType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1PriorityClassListType:
    api_version: str
    items: List[V1PriorityClassType]
    kind: str
    metadata: V1ListMetaType
