# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_pod import V1PodType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1PodListType:
    api_version: str
    items: List[V1PodType]
    kind: str
    metadata: V1ListMetaType
