# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDNSConfigType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_pod_dns_config_option import V1PodDNSConfigOptionType


@dataclass
class V1PodDNSConfigType:
    nameservers: List[str]
    options: List[V1PodDNSConfigOptionType]
    searches: List[str]
