# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityLevelConfigurationStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_priority_level_configuration_condition import V1PriorityLevelConfigurationConditionType


@dataclass
class V1PriorityLevelConfigurationStatusType:
    conditions: List[V1PriorityLevelConfigurationConditionType]
