# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_persistent_volume import V1PersistentVolumeType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1PersistentVolumeListType:
    api_version: str
    items: List[V1PersistentVolumeType]
    kind: str
    metadata: V1ListMetaType
