# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_persistent_volume_spec import V1PersistentVolumeSpecType
from kubernetes_typed.client.models.v1_persistent_volume_status import V1PersistentVolumeStatusType


@dataclass
class V1PersistentVolumeType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1PersistentVolumeSpecType
    status: V1PersistentVolumeStatusType
