# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass
from typing import List

from .v1_pod_condition import V1PodConditionType
from .v1_container_status import V1ContainerStatusType
from .v1_host_ip import V1HostIPType
from .v1_pod_ip import V1PodIPType
from .v1_pod_resource_claim_status import V1PodResourceClaimStatusType


@dataclass
class V1PodStatusType:
    conditions: List[V1PodConditionType]
    container_statuses: List[V1ContainerStatusType]
    ephemeral_container_statuses: List[V1ContainerStatusType]
    host_ip: str
    host_i_ps: List[V1HostIPType]
    init_container_statuses: List[V1ContainerStatusType]
    message: str
    nominated_node_name: str
    phase: str
    pod_ip: str
    pod_i_ps: List[V1PodIPType]
    qos_class: str
    reason: str
    resize: str
    resource_claim_statuses: List[V1PodResourceClaimStatusType]
    start_time: datetime.datetime
