# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimTemplateType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_persistent_volume_claim_spec import V1PersistentVolumeClaimSpecType


@dataclass
class V1PersistentVolumeClaimTemplateType:
    metadata: V1ObjectMetaType
    spec: V1PersistentVolumeClaimSpecType
