# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1PodDisruptionBudgetSpecType:
    max_unavailable: object
    min_available: object
    selector: V1LabelSelectorType
    unhealthy_pod_eviction_policy: str
