# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodFailurePolicyOnPodConditionsPatternType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PodFailurePolicyOnPodConditionsPatternType:
    status: str
    type: str
