# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityClassType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1PriorityClassType:
    apiVersion: str
    description: str
    globalDefault: bool
    kind: str
    metadata: V1ObjectMetaType
    preemptionPolicy: str
    value: int
