# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_pod_spec import V1PodSpecType
from .v1_pod_status import V1PodStatusType


@dataclass
class V1PodType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1PodSpecType
    status: V1PodStatusType
