# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_pod_disruption_budget import V1PodDisruptionBudgetType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1PodDisruptionBudgetListType:
    api_version: str
    items: List[V1PodDisruptionBudgetType]
    kind: str
    metadata: V1ListMetaType
