# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodResourceClaimType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1PodResourceClaimType:
    name: str
    resourceClaimName: str
    resourceClaimTemplateName: str
