# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PriorityClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_priority_class import V1PriorityClassType


@dataclass
class V1PriorityClassListType:
    apiVersion: str
    items: List[V1PriorityClassType]
    kind: str
    metadata: V1ListMetaType
