# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodReadinessGateType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1PodReadinessGateType:
    condition_type: str
