# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodFailurePolicyRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_pod_failure_policy_on_exit_codes_requirement import V1PodFailurePolicyOnExitCodesRequirementType
from .v1_pod_failure_policy_on_pod_conditions_pattern import V1PodFailurePolicyOnPodConditionsPatternType


@dataclass
class V1PodFailurePolicyRuleType:
    action: str
    on_exit_codes: V1PodFailurePolicyOnExitCodesRequirementType
    on_pod_conditions: List[V1PodFailurePolicyOnPodConditionsPatternType]
