# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1QueuingConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1QueuingConfigurationType:
    hand_size: int
    queue_length_limit: int
    queues: int
