# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1QueuingConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1QueuingConfigurationType:
    handSize: int
    queueLengthLimit: int
    queues: int
