# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RuntimeClassType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_overhead import V1OverheadType
from kubernetes_typed.client.models.v1_scheduling import V1SchedulingType


@dataclass
class V1RuntimeClassType:
    apiVersion: str
    handler: str
    kind: str
    metadata: V1ObjectMetaType
    overhead: V1OverheadType
    scheduling: V1SchedulingType
