# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RuntimeClassType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_overhead import V1OverheadType
from .v1_scheduling import V1SchedulingType


@dataclass
class V1RuntimeClassType:
    api_version: str
    handler: str
    kind: str
    metadata: V1ObjectMetaType
    overhead: V1OverheadType
    scheduling: V1SchedulingType
