# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceQuotaListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_resource_quota import V1ResourceQuotaType


@dataclass
class V1ResourceQuotaListType:
    apiVersion: str
    items: List[V1ResourceQuotaType]
    kind: str
    metadata: V1ListMetaType
