# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RollingUpdateDeploymentType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1RollingUpdateDeploymentType:
    maxSurge: object
    maxUnavailable: object
