# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RBDVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1RBDVolumeSourceType:
    fs_type: str
    image: str
    keyring: str
    monitors: List[str]
    pool: str
    read_only: bool
    secret_ref: V1LocalObjectReferenceType
    user: str
