# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_replica_set import V1ReplicaSetType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1ReplicaSetListType:
    api_version: str
    items: List[V1ReplicaSetType]
    kind: str
    metadata: V1ListMetaType
