# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1ReplicationControllerSpecType:
    minReadySeconds: int
    replicas: int
    selector: Dict[str, str]
    template: V1PodTemplateSpecType
