# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RBDVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1RBDVolumeSourceType:
    fsType: str
    image: str
    keyring: str
    monitors: List[str]
    pool: str
    readOnly: bool
    secretRef: V1LocalObjectReferenceType
    user: str
