# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_role import V1RoleType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1RoleListType:
    api_version: str
    items: List[V1RoleType]
    kind: str
    metadata: V1ListMetaType
