# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_replica_set import V1ReplicaSetType


@dataclass
class V1ReplicaSetListType:
    apiVersion: str
    items: List[V1ReplicaSetType]
    kind: str
    metadata: V1ListMetaType
