# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_replication_controller import V1ReplicationControllerType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1ReplicationControllerListType:
    api_version: str
    items: List[V1ReplicationControllerType]
    kind: str
    metadata: V1ListMetaType
