# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_replication_controller_condition import V1ReplicationControllerConditionType


@dataclass
class V1ReplicationControllerStatusType:
    availableReplicas: int
    conditions: List[V1ReplicationControllerConditionType]
    fullyLabeledReplicas: int
    observedGeneration: int
    readyReplicas: int
    replicas: int
