# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_replication_controller_condition import V1ReplicationControllerConditionType


@dataclass
class V1ReplicationControllerStatusType:
    available_replicas: int
    conditions: List[V1ReplicationControllerConditionType]
    fully_labeled_replicas: int
    observed_generation: int
    ready_replicas: int
    replicas: int
