# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_replication_controller import V1ReplicationControllerType


@dataclass
class V1ReplicationControllerListType:
    apiVersion: str
    items: List[V1ReplicationControllerType]
    kind: str
    metadata: V1ListMetaType
