# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceAttributesType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_field_selector_attributes import V1FieldSelectorAttributesType
from kubernetes_typed.client.models.v1_label_selector_attributes import V1LabelSelectorAttributesType


@dataclass
class V1ResourceAttributesType:
    fieldSelector: V1FieldSelectorAttributesType
    group: str
    labelSelector: V1LabelSelectorAttributesType
    name: str
    namespace: str
    resource: str
    subresource: str
    verb: str
    version: str
