# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceFieldSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ResourceFieldSelectorType:
    container_name: str
    divisor: str
    resource: str
