# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RuleWithOperationsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1RuleWithOperationsType:
    api_groups: List[str]
    api_versions: List[str]
    operations: List[str]
    resources: List[str]
    scope: str
