# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceQuotaStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict


@dataclass
class V1ResourceQuotaStatusType:
    hard: Dict[str, str]
    used: Dict[str, str]
