# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleRefType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1RoleRefType:
    api_group: str
    kind: str
    name: str
