# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1ReplicaSetSpecType:
    minReadySeconds: int
    replicas: int
    selector: V1LabelSelectorType
    template: V1PodTemplateSpecType
