# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceQuotaType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_resource_quota_spec import V1ResourceQuotaSpecType
from kubernetes_typed.client.models.v1_resource_quota_status import V1ResourceQuotaStatusType


@dataclass
class V1ResourceQuotaType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1ResourceQuotaSpecType
    status: V1ResourceQuotaStatusType
