# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict

from .v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1ReplicationControllerSpecType:
    min_ready_seconds: int
    replicas: int
    selector: Dict[str, str]
    template: V1PodTemplateSpecType
