# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_label_selector import V1LabelSelectorType
from .v1_pod_template_spec import V1PodTemplateSpecType


@dataclass
class V1ReplicaSetSpecType:
    min_ready_seconds: int
    replicas: int
    selector: V1LabelSelectorType
    template: V1PodTemplateSpecType
