# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_role import V1RoleType


@dataclass
class V1RoleListType:
    apiVersion: str
    items: List[V1RoleType]
    kind: str
    metadata: V1ListMetaType
