# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_replica_set_condition import V1ReplicaSetConditionType


@dataclass
class V1ReplicaSetStatusType:
    available_replicas: int
    conditions: List[V1ReplicaSetConditionType]
    fully_labeled_replicas: int
    observed_generation: int
    ready_replicas: int
    replicas: int
