# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RBDPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_secret_reference import V1SecretReferenceType


@dataclass
class V1RBDPersistentVolumeSourceType:
    fsType: str
    image: str
    keyring: str
    monitors: List[str]
    pool: str
    readOnly: bool
    secretRef: V1SecretReferenceType
    user: str
