# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceQuotaSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_scope_selector import V1ScopeSelectorType


@dataclass
class V1ResourceQuotaSpecType:
    hard: Dict[str, str]
    scopeSelector: V1ScopeSelectorType
    scopes: List[str]
