# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RollingUpdateStatefulSetStrategyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1RollingUpdateStatefulSetStrategyType:
    max_unavailable: object
    partition: int
