# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceRequirementsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_resource_claim import V1ResourceClaimType


@dataclass
class V1ResourceRequirementsType:
    claims: List[V1ResourceClaimType]
    limits: Dict[str, str]
    requests: Dict[str, str]
