# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_replica_set_spec import V1ReplicaSetSpecType
from .v1_replica_set_status import V1ReplicaSetStatusType


@dataclass
class V1ReplicaSetType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1ReplicaSetSpecType
    status: V1ReplicaSetStatusType
