# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_resource_health import V1ResourceHealthType


@dataclass
class V1ResourceStatusType:
    name: str
    resources: List[V1ResourceHealthType]
