# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RuntimeClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_runtime_class import V1RuntimeClassType


@dataclass
class V1RuntimeClassListType:
    apiVersion: str
    items: List[V1RuntimeClassType]
    kind: str
    metadata: V1ListMetaType
