# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_replica_set_condition import V1ReplicaSetConditionType


@dataclass
class V1ReplicaSetStatusType:
    availableReplicas: int
    conditions: List[V1ReplicaSetConditionType]
    fullyLabeledReplicas: int
    observedGeneration: int
    readyReplicas: int
    replicas: int
