# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceQuotaSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict, List

from .v1_scope_selector import V1ScopeSelectorType


@dataclass
class V1ResourceQuotaSpecType:
    hard: Dict[str, str]
    scope_selector: V1ScopeSelectorType
    scopes: List[str]
