# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceHealthType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ResourceHealthType:
    health: str
    resourceID: str
