# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceAttributesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ResourceAttributesType:
    group: str
    name: str
    namespace: str
    resource: str
    subresource: str
    verb: str
    version: str
