# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RBDPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_secret_reference import V1SecretReferenceType


@dataclass
class V1RBDPersistentVolumeSourceType:
    fs_type: str
    image: str
    keyring: str
    monitors: List[str]
    pool: str
    read_only: bool
    secret_ref: V1SecretReferenceType
    user: str
