# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleBindingListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_role_binding import V1RoleBindingType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1RoleBindingListType:
    api_version: str
    items: List[V1RoleBindingType]
    kind: str
    metadata: V1ListMetaType
