# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleBindingListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_role_binding import V1RoleBindingType


@dataclass
class V1RoleBindingListType:
    apiVersion: str
    items: List[V1RoleBindingType]
    kind: str
    metadata: V1ListMetaType
