# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_service_port import V1ServicePortType
from kubernetes_typed.client.models.v1_session_affinity_config import V1SessionAffinityConfigType


@dataclass
class V1ServiceSpecType:
    allocateLoadBalancerNodePorts: bool
    clusterIP: str
    clusterIPs: List[str]
    externalIPs: List[str]
    externalName: str
    externalTrafficPolicy: str
    healthCheckNodePort: int
    internalTrafficPolicy: str
    ipFamilies: List[str]
    ipFamilyPolicy: str
    loadBalancerClass: str
    loadBalancerIP: str
    loadBalancerSourceRanges: List[str]
    ports: List[V1ServicePortType]
    publishNotReadyAddresses: bool
    selector: Dict[str, str]
    sessionAffinity: str
    sessionAffinityConfig: V1SessionAffinityConfigType
    trafficDistribution: str
    type: str
