# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelfSubjectRulesReviewType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_self_subject_rules_review_spec import V1SelfSubjectRulesReviewSpecType
from .v1_subject_rules_review_status import V1SubjectRulesReviewStatusType


@dataclass
class V1SelfSubjectRulesReviewType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1SelfSubjectRulesReviewSpecType
    status: V1SubjectRulesReviewStatusType
