# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelfSubjectAccessReviewSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_non_resource_attributes import V1NonResourceAttributesType
from kubernetes_typed.client.models.v1_resource_attributes import V1ResourceAttributesType


@dataclass
class V1SelfSubjectAccessReviewSpecType:
    nonResourceAttributes: V1NonResourceAttributesType
    resourceAttributes: V1ResourceAttributesType
