# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_storage_class import V1StorageClassType


@dataclass
class V1StorageClassListType:
    apiVersion: str
    items: List[V1StorageClassType]
    kind: str
    metadata: V1ListMetaType
