# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType
from kubernetes_typed.client.models.v1_persistent_volume_claim import V1PersistentVolumeClaimType
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecType
from kubernetes_typed.client.models.v1_stateful_set_ordinals import V1StatefulSetOrdinalsType
from kubernetes_typed.client.models.v1_stateful_set_persistent_volume_claim_retention_policy import V1StatefulSetPersistentVolumeClaimRetentionPolicyType
from kubernetes_typed.client.models.v1_stateful_set_update_strategy import V1StatefulSetUpdateStrategyType


@dataclass
class V1StatefulSetSpecType:
    minReadySeconds: int
    ordinals: V1StatefulSetOrdinalsType
    persistentVolumeClaimRetentionPolicy: V1StatefulSetPersistentVolumeClaimRetentionPolicyType
    podManagementPolicy: str
    replicas: int
    revisionHistoryLimit: int
    selector: V1LabelSelectorType
    serviceName: str
    template: V1PodTemplateSpecType
    updateStrategy: V1StatefulSetUpdateStrategyType
    volumeClaimTemplates: List[V1PersistentVolumeClaimType]
