# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatusCauseType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1StatusCauseType:
    field: str
    message: str
    reason: str
