# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SchedulingType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_toleration import V1TolerationType


@dataclass
class V1SchedulingType:
    nodeSelector: Dict[str, str]
    tolerations: List[V1TolerationType]
