# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServerAddressByClientCIDRType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ServerAddressByClientCIDRType:
    clientCIDR: str
    serverAddress: str
