# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetOrdinalsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1StatefulSetOrdinalsType:
    start: int
