# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServicePortType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ServicePortType:
    app_protocol: str
    name: str
    node_port: int
    port: int
    protocol: str
    target_port: object
