# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_key_to_path import V1KeyToPathType


@dataclass
class V1SecretVolumeSourceType:
    default_mode: int
    items: List[V1KeyToPathType]
    optional: bool
    secret_name: str
