# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_service_spec import V1ServiceSpecType
from kubernetes_typed.client.models.v1_service_status import V1ServiceStatusType


@dataclass
class V1ServiceType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1ServiceSpecType
    status: V1ServiceStatusType
