# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_stateful_set_spec import V1StatefulSetSpecType
from kubernetes_typed.client.models.v1_stateful_set_status import V1StatefulSetStatusType


@dataclass
class V1StatefulSetType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1StatefulSetSpecType
    status: V1StatefulSetStatusType
