# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretEnvSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1SecretEnvSourceType:
    name: str
    optional: bool
