# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelfSubjectReviewStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_user_info import V1UserInfoType


@dataclass
class V1SelfSubjectReviewStatusType:
    user_info: V1UserInfoType
