# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageClassType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_topology_selector_term import V1TopologySelectorTermType


@dataclass
class V1StorageClassType:
    allowVolumeExpansion: bool
    allowedTopologies: List[V1TopologySelectorTermType]
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    mountOptions: List[str]
    parameters: Dict[str, str]
    provisioner: str
    reclaimPolicy: str
    volumeBindingMode: str
