# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServicePortType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ServicePortType:
    appProtocol: str
    name: str
    nodePort: int
    port: int
    protocol: str
    targetPort: object
