# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SubjectRulesReviewStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_non_resource_rule import V1NonResourceRuleType
from .v1_resource_rule import V1ResourceRuleType


@dataclass
class V1SubjectRulesReviewStatusType:
    evaluation_error: str
    incomplete: bool
    non_resource_rules: List[V1NonResourceRuleType]
    resource_rules: List[V1ResourceRuleType]
