# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_secret import V1SecretType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1SecretListType:
    api_version: str
    items: List[V1SecretType]
    kind: str
    metadata: V1ListMetaType
