# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_service import V1ServiceType


@dataclass
class V1ServiceListType:
    apiVersion: str
    items: List[V1ServiceType]
    kind: str
    metadata: V1ListMetaType
