# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatusDetailsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_status_cause import V1StatusCauseType


@dataclass
class V1StatusDetailsType:
    causes: List[V1StatusCauseType]
    group: str
    kind: str
    name: str
    retry_after_seconds: int
    uid: str
