# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScopedResourceSelectorRequirementType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1ScopedResourceSelectorRequirementType:
    operator: str
    scope_name: str
    values: List[str]
