# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretKeySelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1SecretKeySelectorType:
    key: str
    name: str
    optional: bool
