# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_stateful_set import V1StatefulSetType


@dataclass
class V1StatefulSetListType:
    apiVersion: str
    items: List[V1StatefulSetType]
    kind: str
    metadata: V1ListMetaType
