# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageOSPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType


@dataclass
class V1StorageOSPersistentVolumeSourceType:
    fsType: str
    readOnly: bool
    secretRef: V1ObjectReferenceType
    volumeName: str
    volumeNamespace: str
