# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecurityContextType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_capabilities import V1CapabilitiesType
from .v1_se_linux_options import V1SELinuxOptionsType
from .v1_seccomp_profile import V1SeccompProfileType
from .v1_windows_security_context_options import V1WindowsSecurityContextOptionsType


@dataclass
class V1SecurityContextType:
    allow_privilege_escalation: bool
    capabilities: V1CapabilitiesType
    privileged: bool
    proc_mount: str
    read_only_root_filesystem: bool
    run_as_group: int
    run_as_non_root: bool
    run_as_user: int
    se_linux_options: V1SELinuxOptionsType
    seccomp_profile: V1SeccompProfileType
    windows_options: V1WindowsSecurityContextOptionsType
