# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageOSVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1StorageOSVolumeSourceType:
    fs_type: str
    read_only: bool
    secret_ref: V1LocalObjectReferenceType
    volume_name: str
    volume_namespace: str
