# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1SecretReferenceType:
    name: str
    namespace: str
