# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SleepActionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1SleepActionType:
    seconds: int
