# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatusType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_status_details import V1StatusDetailsType


@dataclass
class V1StatusType:
    apiVersion: str
    code: int
    details: V1StatusDetailsType
    kind: str
    message: str
    metadata: V1ListMetaType
    reason: str
    status: str
