# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetPersistentVolumeClaimRetentionPolicyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1StatefulSetPersistentVolumeClaimRetentionPolicyType:
    when_deleted: str
    when_scaled: str
