# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict, List

from .v1_service_port import V1ServicePortType
from .v1_session_affinity_config import V1SessionAffinityConfigType


@dataclass
class V1ServiceSpecType:
    allocate_load_balancer_node_ports: bool
    cluster_ip: str
    cluster_i_ps: List[str]
    external_i_ps: List[str]
    external_name: str
    external_traffic_policy: str
    health_check_node_port: int
    internal_traffic_policy: str
    ip_families: List[str]
    ip_family_policy: str
    load_balancer_class: str
    load_balancer_ip: str
    load_balancer_source_ranges: List[str]
    ports: List[V1ServicePortType]
    publish_not_ready_addresses: bool
    selector: Dict[str, str]
    session_affinity: str
    session_affinity_config: V1SessionAffinityConfigType
    type: str
