# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_stateful_set_ordinals import V1StatefulSetOrdinalsType
from .v1_stateful_set_persistent_volume_claim_retention_policy import V1StatefulSetPersistentVolumeClaimRetentionPolicyType
from .v1_label_selector import V1LabelSelectorType
from .v1_pod_template_spec import V1PodTemplateSpecType
from .v1_stateful_set_update_strategy import V1StatefulSetUpdateStrategyType
from .v1_persistent_volume_claim import V1PersistentVolumeClaimType


@dataclass
class V1StatefulSetSpecType:
    min_ready_seconds: int
    ordinals: V1StatefulSetOrdinalsType
    persistent_volume_claim_retention_policy: V1StatefulSetPersistentVolumeClaimRetentionPolicyType
    pod_management_policy: str
    replicas: int
    revision_history_limit: int
    selector: V1LabelSelectorType
    service_name: str
    template: V1PodTemplateSpecType
    update_strategy: V1StatefulSetUpdateStrategyType
    volume_claim_templates: List[V1PersistentVolumeClaimType]
