# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceType


@dataclass
class V1ServiceAccountType:
    apiVersion: str
    automountServiceAccountToken: bool
    imagePullSecrets: List[V1LocalObjectReferenceType]
    kind: str
    metadata: V1ObjectMetaType
    secrets: List[V1ObjectReferenceType]
