# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SuccessPolicyRuleType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1SuccessPolicyRuleType:
    succeededCount: int
    succeededIndexes: str
