# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SessionAffinityConfigType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_client_ip_config import V1ClientIPConfigType


@dataclass
class V1SessionAffinityConfigType:
    client_ip: V1ClientIPConfigType
