# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ScaleSpecType:
    replicas: int
