# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelectableFieldType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1SelectableFieldType:
    jsonPath: str
