# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleIOPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_secret_reference import V1SecretReferenceType


@dataclass
class V1ScaleIOPersistentVolumeSourceType:
    fsType: str
    gateway: str
    protectionDomain: str
    readOnly: bool
    secretRef: V1SecretReferenceType
    sslEnabled: bool
    storageMode: str
    storagePool: str
    system: str
    volumeName: str
