# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_condition import V1ConditionType
from kubernetes_typed.client.models.v1_load_balancer_status import V1LoadBalancerStatusType


@dataclass
class V1ServiceStatusType:
    conditions: List[V1ConditionType]
    loadBalancer: V1LoadBalancerStatusType
