# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict

from .v1_object_meta import V1ObjectMetaType


@dataclass
class V1SecretType:
    api_version: str
    data: Dict[str, str]
    immutable: bool
    kind: str
    metadata: V1ObjectMetaType
    string_data: Dict[str, str]
    type: str
