# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SubjectAccessReviewType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_subject_access_review_spec import V1SubjectAccessReviewSpecType
from kubernetes_typed.client.models.v1_subject_access_review_status import V1SubjectAccessReviewStatusType


@dataclass
class V1SubjectAccessReviewType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1SubjectAccessReviewSpecType
    status: V1SubjectAccessReviewStatusType
