# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SeccompProfileType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1SeccompProfileType:
    localhost_profile: str
    type: str
