# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScopeSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_scoped_resource_selector_requirement import V1ScopedResourceSelectorRequirementType


@dataclass
class V1ScopeSelectorType:
    matchExpressions: List[V1ScopedResourceSelectorRequirementType]
