# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SubjectAccessReviewStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1SubjectAccessReviewStatusType:
    allowed: bool
    denied: bool
    evaluation_error: str
    reason: str
