# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SuccessPolicyType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_success_policy_rule import V1SuccessPolicyRuleType


@dataclass
class V1SuccessPolicyType:
    rules: List[V1SuccessPolicyRuleType]
