# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScopedResourceSelectorRequirementType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1ScopedResourceSelectorRequirementType:
    operator: str
    scopeName: str
    values: List[str]
