# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleIOPersistentVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_secret_reference import V1SecretReferenceType


@dataclass
class V1ScaleIOPersistentVolumeSourceType:
    fs_type: str
    gateway: str
    protection_domain: str
    read_only: bool
    secret_ref: V1SecretReferenceType
    ssl_enabled: bool
    storage_mode: str
    storage_pool: str
    system: str
    volume_name: str
