# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SubjectAccessReviewSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict, List

from .v1_non_resource_attributes import V1NonResourceAttributesType
from .v1_resource_attributes import V1ResourceAttributesType


@dataclass
class V1SubjectAccessReviewSpecType:
    extra: Dict[str, List[str]]
    groups: List[str]
    non_resource_attributes: V1NonResourceAttributesType
    resource_attributes: V1ResourceAttributesType
    uid: str
    user: str
