# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_condition import V1ConditionType
from .v1_load_balancer_status import V1LoadBalancerStatusType


@dataclass
class V1ServiceStatusType:
    conditions: List[V1ConditionType]
    load_balancer: V1LoadBalancerStatusType
