# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_storage_class import V1StorageClassType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1StorageClassListType:
    api_version: str
    items: List[V1StorageClassType]
    kind: str
    metadata: V1ListMetaType
