# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountTokenProjectionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ServiceAccountTokenProjectionType:
    audience: str
    expiration_seconds: int
    path: str
