# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_service_account import V1ServiceAccountType


@dataclass
class V1ServiceAccountListType:
    apiVersion: str
    items: List[V1ServiceAccountType]
    kind: str
    metadata: V1ListMetaType
