# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceBackendPortType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ServiceBackendPortType:
    name: str
    number: int
