# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_secret import V1SecretType


@dataclass
class V1SecretListType:
    apiVersion: str
    items: List[V1SecretType]
    kind: str
    metadata: V1ListMetaType
