# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_stateful_set_condition import V1StatefulSetConditionType


@dataclass
class V1StatefulSetStatusType:
    availableReplicas: int
    collisionCount: int
    conditions: List[V1StatefulSetConditionType]
    currentReplicas: int
    currentRevision: str
    observedGeneration: int
    readyReplicas: int
    replicas: int
    updateRevision: str
    updatedReplicas: int
