# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SchedulingType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict, List

from .v1_toleration import V1TolerationType


@dataclass
class V1SchedulingType:
    node_selector: Dict[str, str]
    tolerations: List[V1TolerationType]
