# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleIOVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1ScaleIOVolumeSourceType:
    fs_type: str
    gateway: str
    protection_domain: str
    read_only: bool
    secret_ref: V1LocalObjectReferenceType
    ssl_enabled: bool
    storage_mode: str
    storage_pool: str
    system: str
    volume_name: str
