# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_stateful_set import V1StatefulSetType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1StatefulSetListType:
    api_version: str
    items: List[V1StatefulSetType]
    kind: str
    metadata: V1ListMetaType
