# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1SecretType:
    apiVersion: str
    data: Dict[str, str]
    immutable: bool
    kind: str
    metadata: V1ObjectMetaType
    stringData: Dict[str, str]
    type: str
