# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelfSubjectAccessReviewSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_non_resource_attributes import V1NonResourceAttributesType
from .v1_resource_attributes import V1ResourceAttributesType


@dataclass
class V1SelfSubjectAccessReviewSpecType:
    non_resource_attributes: V1NonResourceAttributesType
    resource_attributes: V1ResourceAttributesType
