# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SELinuxOptionsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1SELinuxOptionsType:
    level: str
    role: str
    type: str
    user: str
