# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ScaleStatusType:
    replicas: int
    selector: str
