# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SubjectRulesReviewStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_non_resource_rule import V1NonResourceRuleType
from kubernetes_typed.client.models.v1_resource_rule import V1ResourceRuleType


@dataclass
class V1SubjectRulesReviewStatusType:
    evaluationError: str
    incomplete: bool
    nonResourceRules: List[V1NonResourceRuleType]
    resourceRules: List[V1ResourceRuleType]
