# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatusDetailsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_status_cause import V1StatusCauseType


@dataclass
class V1StatusDetailsType:
    causes: List[V1StatusCauseType]
    group: str
    kind: str
    name: str
    retryAfterSeconds: int
    uid: str
