# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_local_object_reference import V1LocalObjectReferenceType
from .v1_object_meta import V1ObjectMetaType
from .v1_object_reference import V1ObjectReferenceType


@dataclass
class V1ServiceAccountType:
    api_version: str
    automount_service_account_token: bool
    image_pull_secrets: List[V1LocalObjectReferenceType]
    kind: str
    metadata: V1ObjectMetaType
    secrets: List[V1ObjectReferenceType]
