# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_service_account import V1ServiceAccountType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1ServiceAccountListType:
    api_version: str
    items: List[V1ServiceAccountType]
    kind: str
    metadata: V1ListMetaType
