# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecurityContextType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_app_armor_profile import V1AppArmorProfileType
from kubernetes_typed.client.models.v1_capabilities import V1CapabilitiesType
from kubernetes_typed.client.models.v1_se_linux_options import V1SELinuxOptionsType
from kubernetes_typed.client.models.v1_seccomp_profile import V1SeccompProfileType
from kubernetes_typed.client.models.v1_windows_security_context_options import V1WindowsSecurityContextOptionsType


@dataclass
class V1SecurityContextType:
    allowPrivilegeEscalation: bool
    appArmorProfile: V1AppArmorProfileType
    capabilities: V1CapabilitiesType
    privileged: bool
    procMount: str
    readOnlyRootFilesystem: bool
    runAsGroup: int
    runAsNonRoot: bool
    runAsUser: int
    seLinuxOptions: V1SELinuxOptionsType
    seccompProfile: V1SeccompProfileType
    windowsOptions: V1WindowsSecurityContextOptionsType
