# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScopeSelectorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_scoped_resource_selector_requirement import V1ScopedResourceSelectorRequirementType


@dataclass
class V1ScopeSelectorType:
    match_expressions: List[V1ScopedResourceSelectorRequirementType]
