# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetUpdateStrategyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_rolling_update_stateful_set_strategy import V1RollingUpdateStatefulSetStrategyType


@dataclass
class V1StatefulSetUpdateStrategyType:
    rolling_update: V1RollingUpdateStatefulSetStrategyType
    type: str
