# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleIOVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceType


@dataclass
class V1ScaleIOVolumeSourceType:
    fsType: str
    gateway: str
    protectionDomain: str
    readOnly: bool
    secretRef: V1LocalObjectReferenceType
    sslEnabled: bool
    storageMode: str
    storagePool: str
    system: str
    volumeName: str
