# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountSubjectType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1ServiceAccountSubjectType:
    name: str
    namespace: str
