# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TopologySelectorTermType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_topology_selector_label_requirement import V1TopologySelectorLabelRequirementType


@dataclass
class V1TopologySelectorTermType:
    matchLabelExpressions: List[V1TopologySelectorLabelRequirementType]
