# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenReviewType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1_token_review_spec import V1TokenReviewSpecType
from .v1_token_review_status import V1TokenReviewStatusType


@dataclass
class V1TokenReviewType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1TokenReviewSpecType
    status: V1TokenReviewStatusType
