# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenReviewType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_token_review_spec import V1TokenReviewSpecType
from kubernetes_typed.client.models.v1_token_review_status import V1TokenReviewStatusType


@dataclass
class V1TokenReviewType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1TokenReviewSpecType
    status: V1TokenReviewStatusType
