# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TopologySelectorTermType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_topology_selector_label_requirement import V1TopologySelectorLabelRequirementType


@dataclass
class V1TopologySelectorTermType:
    match_label_expressions: List[V1TopologySelectorLabelRequirementType]
