# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TypedLocalObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1TypedLocalObjectReferenceType:
    apiGroup: str
    kind: str
    name: str
