# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TopologySpreadConstraintType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1TopologySpreadConstraintType:
    label_selector: V1LabelSelectorType
    match_label_keys: List[str]
    max_skew: int
    min_domains: int
    node_affinity_policy: str
    node_taints_policy: str
    topology_key: str
    when_unsatisfiable: str
