# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenReviewStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_user_info import V1UserInfoType


@dataclass
class V1TokenReviewStatusType:
    audiences: List[str]
    authenticated: bool
    error: str
    user: V1UserInfoType
