# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TCPSocketActionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1TCPSocketActionType:
    host: str
    port: object
