# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenRequestSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_bound_object_reference import V1BoundObjectReferenceType


@dataclass
class V1TokenRequestSpecType:
    audiences: List[str]
    bound_object_ref: V1BoundObjectReferenceType
    expiration_seconds: int
