# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenRequestStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1TokenRequestStatusType:
    expiration_timestamp: datetime.datetime
    token: str
