# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TolerationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1TolerationType:
    effect: str
    key: str
    operator: str
    toleration_seconds: int
    value: str
