# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenReviewSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1TokenReviewSpecType:
    audiences: List[str]
    token: str
