# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TypedObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1TypedObjectReferenceType:
    apiGroup: str
    kind: str
    name: str
    namespace: str
