# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TypedObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1TypedObjectReferenceType:
    api_group: str
    kind: str
    name: str
    namespace: str
