# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TaintType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1TaintType:
    effect: str
    key: str
    time_added: datetime.datetime
    value: str
