# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenRequestSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_bound_object_reference import V1BoundObjectReferenceType


@dataclass
class V1TokenRequestSpecType:
    audiences: List[str]
    boundObjectRef: V1BoundObjectReferenceType
    expirationSeconds: int
