# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1UncountedTerminatedPodsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1UncountedTerminatedPodsType:
    failed: List[str]
    succeeded: List[str]
