# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1UncountedTerminatedPodsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1UncountedTerminatedPodsType:
    failed: List[str]
    succeeded: List[str]
