# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1UserInfoType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict, List

from dataclasses import dataclass


@dataclass
class V1UserInfoType:
    extra: Dict[str, List[str]]
    groups: List[str]
    uid: str
    username: str
