# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeErrorType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from dataclasses import dataclass


@dataclass
class V1VolumeErrorType:
    message: str
    time: datetime.datetime
