# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_volume_error import V1VolumeErrorType


@dataclass
class V1VolumeAttachmentStatusType:
    attachError: V1VolumeErrorType
    attached: bool
    attachmentMetadata: Dict[str, str]
    detachError: V1VolumeErrorType
