# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeDeviceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1VolumeDeviceType:
    device_path: str
    name: str
