# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingWebhookConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_object_meta import V1ObjectMetaType
from .v1_validating_webhook import V1ValidatingWebhookType


@dataclass
class V1ValidatingWebhookConfigurationType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    webhooks: List[V1ValidatingWebhookType]
