# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_volume_attachment import V1VolumeAttachmentType


@dataclass
class V1VolumeAttachmentListType:
    apiVersion: str
    items: List[V1VolumeAttachmentType]
    kind: str
    metadata: V1ListMetaType
