# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ValidationType:
    expression: str
    message: str
    messageExpression: str
    reason: str
