# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_volume_attachment_spec import V1VolumeAttachmentSpecType
from kubernetes_typed.client.models.v1_volume_attachment_status import V1VolumeAttachmentStatusType


@dataclass
class V1VolumeAttachmentType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1VolumeAttachmentSpecType
    status: V1VolumeAttachmentStatusType
