# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeMountType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1VolumeMountType:
    mount_path: str
    mount_propagation: str
    name: str
    read_only: bool
    sub_path: str
    sub_path_expr: str
