# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_aws_elastic_block_store_volume_source import V1AWSElasticBlockStoreVolumeSourceType
from kubernetes_typed.client.models.v1_azure_disk_volume_source import V1AzureDiskVolumeSourceType
from kubernetes_typed.client.models.v1_azure_file_volume_source import V1AzureFileVolumeSourceType
from kubernetes_typed.client.models.v1_ceph_fs_volume_source import V1CephFSVolumeSourceType
from kubernetes_typed.client.models.v1_cinder_volume_source import V1CinderVolumeSourceType
from kubernetes_typed.client.models.v1_config_map_volume_source import V1ConfigMapVolumeSourceType
from kubernetes_typed.client.models.v1_csi_volume_source import V1CSIVolumeSourceType
from kubernetes_typed.client.models.v1_downward_api_volume_source import V1DownwardAPIVolumeSourceType
from kubernetes_typed.client.models.v1_empty_dir_volume_source import V1EmptyDirVolumeSourceType
from kubernetes_typed.client.models.v1_ephemeral_volume_source import V1EphemeralVolumeSourceType
from kubernetes_typed.client.models.v1_fc_volume_source import V1FCVolumeSourceType
from kubernetes_typed.client.models.v1_flex_volume_source import V1FlexVolumeSourceType
from kubernetes_typed.client.models.v1_flocker_volume_source import V1FlockerVolumeSourceType
from kubernetes_typed.client.models.v1_gce_persistent_disk_volume_source import V1GCEPersistentDiskVolumeSourceType
from kubernetes_typed.client.models.v1_git_repo_volume_source import V1GitRepoVolumeSourceType
from kubernetes_typed.client.models.v1_glusterfs_volume_source import V1GlusterfsVolumeSourceType
from kubernetes_typed.client.models.v1_host_path_volume_source import V1HostPathVolumeSourceType
from kubernetes_typed.client.models.v1_image_volume_source import V1ImageVolumeSourceType
from kubernetes_typed.client.models.v1_iscsi_volume_source import V1ISCSIVolumeSourceType
from kubernetes_typed.client.models.v1_nfs_volume_source import V1NFSVolumeSourceType
from kubernetes_typed.client.models.v1_persistent_volume_claim_volume_source import V1PersistentVolumeClaimVolumeSourceType
from kubernetes_typed.client.models.v1_photon_persistent_disk_volume_source import V1PhotonPersistentDiskVolumeSourceType
from kubernetes_typed.client.models.v1_portworx_volume_source import V1PortworxVolumeSourceType
from kubernetes_typed.client.models.v1_projected_volume_source import V1ProjectedVolumeSourceType
from kubernetes_typed.client.models.v1_quobyte_volume_source import V1QuobyteVolumeSourceType
from kubernetes_typed.client.models.v1_rbd_volume_source import V1RBDVolumeSourceType
from kubernetes_typed.client.models.v1_scale_io_volume_source import V1ScaleIOVolumeSourceType
from kubernetes_typed.client.models.v1_secret_volume_source import V1SecretVolumeSourceType
from kubernetes_typed.client.models.v1_storage_os_volume_source import V1StorageOSVolumeSourceType
from kubernetes_typed.client.models.v1_vsphere_virtual_disk_volume_source import V1VsphereVirtualDiskVolumeSourceType


@dataclass
class V1VolumeType:
    awsElasticBlockStore: V1AWSElasticBlockStoreVolumeSourceType
    azureDisk: V1AzureDiskVolumeSourceType
    azureFile: V1AzureFileVolumeSourceType
    cephfs: V1CephFSVolumeSourceType
    cinder: V1CinderVolumeSourceType
    configMap: V1ConfigMapVolumeSourceType
    csi: V1CSIVolumeSourceType
    downwardAPI: V1DownwardAPIVolumeSourceType
    emptyDir: V1EmptyDirVolumeSourceType
    ephemeral: V1EphemeralVolumeSourceType
    fc: V1FCVolumeSourceType
    flexVolume: V1FlexVolumeSourceType
    flocker: V1FlockerVolumeSourceType
    gcePersistentDisk: V1GCEPersistentDiskVolumeSourceType
    gitRepo: V1GitRepoVolumeSourceType
    glusterfs: V1GlusterfsVolumeSourceType
    hostPath: V1HostPathVolumeSourceType
    image: V1ImageVolumeSourceType
    iscsi: V1ISCSIVolumeSourceType
    name: str
    nfs: V1NFSVolumeSourceType
    persistentVolumeClaim: V1PersistentVolumeClaimVolumeSourceType
    photonPersistentDisk: V1PhotonPersistentDiskVolumeSourceType
    portworxVolume: V1PortworxVolumeSourceType
    projected: V1ProjectedVolumeSourceType
    quobyte: V1QuobyteVolumeSourceType
    rbd: V1RBDVolumeSourceType
    scaleIO: V1ScaleIOVolumeSourceType
    secret: V1SecretVolumeSourceType
    storageos: V1StorageOSVolumeSourceType
    vsphereVolume: V1VsphereVirtualDiskVolumeSourceType
