# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeMountStatusType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1VolumeMountStatusType:
    mountPath: str
    name: str
    readOnly: bool
    recursiveReadOnly: str
