# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeMountType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1VolumeMountType:
    mountPath: str
    mountPropagation: str
    name: str
    readOnly: bool
    recursiveReadOnly: str
    subPath: str
    subPathExpr: str
