# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_aws_elastic_block_store_volume_source import V1AWSElasticBlockStoreVolumeSourceType
from .v1_azure_disk_volume_source import V1AzureDiskVolumeSourceType
from .v1_azure_file_volume_source import V1AzureFileVolumeSourceType
from .v1_ceph_fs_volume_source import V1CephFSVolumeSourceType
from .v1_cinder_volume_source import V1CinderVolumeSourceType
from .v1_config_map_volume_source import V1ConfigMapVolumeSourceType
from .v1_csi_volume_source import V1CSIVolumeSourceType
from .v1_downward_api_volume_source import V1DownwardAPIVolumeSourceType
from .v1_empty_dir_volume_source import V1EmptyDirVolumeSourceType
from .v1_ephemeral_volume_source import V1EphemeralVolumeSourceType
from .v1_fc_volume_source import V1FCVolumeSourceType
from .v1_flex_volume_source import V1FlexVolumeSourceType
from .v1_flocker_volume_source import V1FlockerVolumeSourceType
from .v1_gce_persistent_disk_volume_source import V1GCEPersistentDiskVolumeSourceType
from .v1_git_repo_volume_source import V1GitRepoVolumeSourceType
from .v1_glusterfs_volume_source import V1GlusterfsVolumeSourceType
from .v1_host_path_volume_source import V1HostPathVolumeSourceType
from .v1_iscsi_volume_source import V1ISCSIVolumeSourceType
from .v1_nfs_volume_source import V1NFSVolumeSourceType
from .v1_persistent_volume_claim_volume_source import V1PersistentVolumeClaimVolumeSourceType
from .v1_photon_persistent_disk_volume_source import V1PhotonPersistentDiskVolumeSourceType
from .v1_portworx_volume_source import V1PortworxVolumeSourceType
from .v1_projected_volume_source import V1ProjectedVolumeSourceType
from .v1_quobyte_volume_source import V1QuobyteVolumeSourceType
from .v1_rbd_volume_source import V1RBDVolumeSourceType
from .v1_scale_io_volume_source import V1ScaleIOVolumeSourceType
from .v1_secret_volume_source import V1SecretVolumeSourceType
from .v1_storage_os_volume_source import V1StorageOSVolumeSourceType
from .v1_vsphere_virtual_disk_volume_source import V1VsphereVirtualDiskVolumeSourceType


@dataclass
class V1VolumeType:
    aws_elastic_block_store: V1AWSElasticBlockStoreVolumeSourceType
    azure_disk: V1AzureDiskVolumeSourceType
    azure_file: V1AzureFileVolumeSourceType
    cephfs: V1CephFSVolumeSourceType
    cinder: V1CinderVolumeSourceType
    config_map: V1ConfigMapVolumeSourceType
    csi: V1CSIVolumeSourceType
    downward_api: V1DownwardAPIVolumeSourceType
    empty_dir: V1EmptyDirVolumeSourceType
    ephemeral: V1EphemeralVolumeSourceType
    fc: V1FCVolumeSourceType
    flex_volume: V1FlexVolumeSourceType
    flocker: V1FlockerVolumeSourceType
    gce_persistent_disk: V1GCEPersistentDiskVolumeSourceType
    git_repo: V1GitRepoVolumeSourceType
    glusterfs: V1GlusterfsVolumeSourceType
    host_path: V1HostPathVolumeSourceType
    iscsi: V1ISCSIVolumeSourceType
    name: str
    nfs: V1NFSVolumeSourceType
    persistent_volume_claim: V1PersistentVolumeClaimVolumeSourceType
    photon_persistent_disk: V1PhotonPersistentDiskVolumeSourceType
    portworx_volume: V1PortworxVolumeSourceType
    projected: V1ProjectedVolumeSourceType
    quobyte: V1QuobyteVolumeSourceType
    rbd: V1RBDVolumeSourceType
    scale_io: V1ScaleIOVolumeSourceType
    secret: V1SecretVolumeSourceType
    storageos: V1StorageOSVolumeSourceType
    vsphere_volume: V1VsphereVirtualDiskVolumeSourceType
