# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_volume_attachment_source import V1VolumeAttachmentSourceType


@dataclass
class V1VolumeAttachmentSpecType:
    attacher: str
    nodeName: str
    source: V1VolumeAttachmentSourceType
