# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeProjectionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_cluster_trust_bundle_projection import V1ClusterTrustBundleProjectionType
from .v1_config_map_projection import V1ConfigMapProjectionType
from .v1_downward_api_projection import V1DownwardAPIProjectionType
from .v1_secret_projection import V1SecretProjectionType
from .v1_service_account_token_projection import V1ServiceAccountTokenProjectionType


@dataclass
class V1VolumeProjectionType:
    cluster_trust_bundle: V1ClusterTrustBundleProjectionType
    config_map: V1ConfigMapProjectionType
    downward_api: V1DownwardAPIProjectionType
    secret: V1SecretProjectionType
    service_account_token: V1ServiceAccountTokenProjectionType
