# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_persistent_volume_spec import V1PersistentVolumeSpecType


@dataclass
class V1VolumeAttachmentSourceType:
    inlineVolumeSpec: V1PersistentVolumeSpecType
    persistentVolumeName: str
