# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingWebhookConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_validating_webhook_configuration import V1ValidatingWebhookConfigurationType


@dataclass
class V1ValidatingWebhookConfigurationListType:
    apiVersion: str
    items: List[V1ValidatingWebhookConfigurationType]
    kind: str
    metadata: V1ListMetaType
