# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeProjectionType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_cluster_trust_bundle_projection import V1ClusterTrustBundleProjectionType
from kubernetes_typed.client.models.v1_config_map_projection import V1ConfigMapProjectionType
from kubernetes_typed.client.models.v1_downward_api_projection import V1DownwardAPIProjectionType
from kubernetes_typed.client.models.v1_secret_projection import V1SecretProjectionType
from kubernetes_typed.client.models.v1_service_account_token_projection import V1ServiceAccountTokenProjectionType


@dataclass
class V1VolumeProjectionType:
    clusterTrustBundle: V1ClusterTrustBundleProjectionType
    configMap: V1ConfigMapProjectionType
    downwardAPI: V1DownwardAPIProjectionType
    secret: V1SecretProjectionType
    serviceAccountToken: V1ServiceAccountTokenProjectionType
