# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingAdmissionPolicySpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_audit_annotation import V1AuditAnnotationType
from kubernetes_typed.client.models.v1_match_condition import V1MatchConditionType
from kubernetes_typed.client.models.v1_match_resources import V1MatchResourcesType
from kubernetes_typed.client.models.v1_param_kind import V1ParamKindType
from kubernetes_typed.client.models.v1_validation import V1ValidationType
from kubernetes_typed.client.models.v1_variable import V1VariableType


@dataclass
class V1ValidatingAdmissionPolicySpecType:
    auditAnnotations: List[V1AuditAnnotationType]
    failurePolicy: str
    matchConditions: List[V1MatchConditionType]
    matchConstraints: V1MatchResourcesType
    paramKind: V1ParamKindType
    validations: List[V1ValidationType]
    variables: List[V1VariableType]
