# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingAdmissionPolicyBindingSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_match_resources import V1MatchResourcesType
from kubernetes_typed.client.models.v1_param_ref import V1ParamRefType


@dataclass
class V1ValidatingAdmissionPolicyBindingSpecType:
    matchResources: V1MatchResourcesType
    paramRef: V1ParamRefType
    policyName: str
    validationActions: List[str]
