# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidationRuleType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1ValidationRuleType:
    fieldPath: str
    message: str
    messageExpression: str
    optionalOldSelf: bool
    reason: str
    rule: str
