# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_persistent_volume_spec import V1PersistentVolumeSpecType


@dataclass
class V1VolumeAttachmentSourceType:
    inline_volume_spec: V1PersistentVolumeSpecType
    persistent_volume_name: str
