# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VsphereVirtualDiskVolumeSourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1VsphereVirtualDiskVolumeSourceType:
    fsType: str
    storagePolicyID: str
    storagePolicyName: str
    volumePath: str
