# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingAdmissionPolicyListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1_validating_admission_policy import V1ValidatingAdmissionPolicyType


@dataclass
class V1ValidatingAdmissionPolicyListType:
    apiVersion: str
    items: List[V1ValidatingAdmissionPolicyType]
    kind: str
    metadata: V1ListMetaType
