# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingWebhookConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_validating_webhook_configuration import V1ValidatingWebhookConfigurationType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1ValidatingWebhookConfigurationListType:
    api_version: str
    items: List[V1ValidatingWebhookConfigurationType]
    kind: str
    metadata: V1ListMetaType
