# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingAdmissionPolicyType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_validating_admission_policy_spec import V1ValidatingAdmissionPolicySpecType
from kubernetes_typed.client.models.v1_validating_admission_policy_status import V1ValidatingAdmissionPolicyStatusType


@dataclass
class V1ValidatingAdmissionPolicyType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1ValidatingAdmissionPolicySpecType
    status: V1ValidatingAdmissionPolicyStatusType
