# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingWebhookConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1_validating_webhook import V1ValidatingWebhookType


@dataclass
class V1ValidatingWebhookConfigurationType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    webhooks: List[V1ValidatingWebhookType]
