# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import Dict

from .v1_volume_error import V1VolumeErrorType


@dataclass
class V1VolumeAttachmentStatusType:
    attach_error: V1VolumeErrorType
    attached: bool
    attachment_metadata: Dict[str, str]
    detach_error: V1VolumeErrorType
