# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WeightedPodAffinityTermType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_pod_affinity_term import V1PodAffinityTermType


@dataclass
class V1WeightedPodAffinityTermType:
    pod_affinity_term: V1PodAffinityTermType
    weight: int
