# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WindowsSecurityContextOptionsType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1WindowsSecurityContextOptionsType:
    gmsaCredentialSpec: str
    gmsaCredentialSpecName: str
    hostProcess: bool
    runAsUserName: str
