# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WatchEventType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1WatchEventType:
    object: object
    type: str
