# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WindowsSecurityContextOptionsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1WindowsSecurityContextOptionsType:
    gmsa_credential_spec: str
    gmsa_credential_spec_name: str
    host_process: bool
    run_as_user_name: str
