# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WebhookConversionType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.apiextensions_v1_webhook_client_config import ApiextensionsV1WebhookClientConfigType


@dataclass
class V1WebhookConversionType:
    clientConfig: ApiextensionsV1WebhookClientConfigType
    conversionReviewVersions: List[str]
