# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceClaimConsumerReferenceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1alpha3ResourceClaimConsumerReferenceType:
    apiGroup: str
    name: str
    resource: str
    uid: str
