# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ServerStorageVersionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1alpha1ServerStorageVersionType:
    api_server_id: str
    decodable_versions: List[str]
    encoding_version: str
    served_versions: List[str]
