# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceClaimType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha2_resource_claim_spec import V1alpha2ResourceClaimSpecType
from .v1alpha2_resource_claim_status import V1alpha2ResourceClaimStatusType


@dataclass
class V1alpha2ResourceClaimType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha2ResourceClaimSpecType
    status: V1alpha2ResourceClaimStatusType
