# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceClassType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha2_resource_class_parameters_reference import V1alpha2ResourceClassParametersReferenceType
from .v1_node_selector import V1NodeSelectorType


@dataclass
class V1alpha2ResourceClassType:
    api_version: str
    driver_name: str
    kind: str
    metadata: V1ObjectMetaType
    parameters_ref: V1alpha2ResourceClassParametersReferenceType
    suitable_nodes: V1NodeSelectorType
