# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceSliceListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha3_resource_slice import V1alpha3ResourceSliceType


@dataclass
class V1alpha3ResourceSliceListType:
    apiVersion: str
    items: List[V1alpha3ResourceSliceType]
    kind: str
    metadata: V1ListMetaType
