# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceAttributeType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1alpha3DeviceAttributeType:
    bool: bool
    int: int
    string: str
    version: str
