# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceClaimSchedulingStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1alpha2ResourceClaimSchedulingStatusType:
    name: str
    unsuitable_nodes: List[str]
