# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceClaimStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_allocation_result import V1alpha3AllocationResultType
from kubernetes_typed.client.models.v1alpha3_resource_claim_consumer_reference import V1alpha3ResourceClaimConsumerReferenceType


@dataclass
class V1alpha3ResourceClaimStatusType:
    allocation: V1alpha3AllocationResultType
    deallocationRequested: bool
    reservedFor: List[V1alpha3ResourceClaimConsumerReferenceType]
