# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceClaimTemplateType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1alpha3_resource_claim_template_spec import V1alpha3ResourceClaimTemplateSpecType


@dataclass
class V1alpha3ResourceClaimTemplateType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha3ResourceClaimTemplateSpecType
