# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2PodSchedulingContextListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1alpha2_pod_scheduling_context import V1alpha2PodSchedulingContextType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1alpha2PodSchedulingContextListType:
    api_version: str
    items: List[V1alpha2PodSchedulingContextType]
    kind: str
    metadata: V1ListMetaType
