# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceSliceSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_selector import V1NodeSelectorType
from kubernetes_typed.client.models.v1alpha3_device import V1alpha3DeviceType
from kubernetes_typed.client.models.v1alpha3_resource_pool import V1alpha3ResourcePoolType


@dataclass
class V1alpha3ResourceSliceSpecType:
    allNodes: bool
    devices: List[V1alpha3DeviceType]
    driver: str
    nodeName: str
    nodeSelector: V1NodeSelectorType
    pool: V1alpha3ResourcePoolType
