# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1MigrationConditionType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1alpha1MigrationConditionType:
    lastUpdateTime: datetime.datetime
    message: str
    reason: str
    status: str
    type: str
