# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ParentReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1alpha1ParentReferenceType:
    group: str
    name: str
    namespace: str
    resource: str
