# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1MatchResourcesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1alpha1_named_rule_with_operations import V1alpha1NamedRuleWithOperationsType
from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1alpha1MatchResourcesType:
    exclude_resource_rules: List[V1alpha1NamedRuleWithOperationsType]
    match_policy: str
    namespace_selector: V1LabelSelectorType
    object_selector: V1LabelSelectorType
    resource_rules: List[V1alpha1NamedRuleWithOperationsType]
