# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1IPAddressSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1alpha1_parent_reference import V1alpha1ParentReferenceType


@dataclass
class V1alpha1IPAddressSpecType:
    parent_ref: V1alpha1ParentReferenceType
