# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceClaimConsumerReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1alpha2ResourceClaimConsumerReferenceType:
    api_group: str
    name: str
    resource: str
    uid: str
