# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1LeaseCandidateType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1alpha1_lease_candidate_spec import V1alpha1LeaseCandidateSpecType


@dataclass
class V1alpha1LeaseCandidateType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha1LeaseCandidateSpecType
