# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1GroupVersionResourceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V1alpha1GroupVersionResourceType:
    group: str
    resource: str
    version: str
