# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3PodSchedulingContextStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_resource_claim_scheduling_status import V1alpha3ResourceClaimSchedulingStatusType


@dataclass
class V1alpha3PodSchedulingContextStatusType:
    resourceClaims: List[V1alpha3ResourceClaimSchedulingStatusType]
