# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1VolumeAttributesClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha1_volume_attributes_class import V1alpha1VolumeAttributesClassType


@dataclass
class V1alpha1VolumeAttributesClassListType:
    apiVersion: str
    items: List[V1alpha1VolumeAttributesClassType]
    kind: str
    metadata: V1ListMetaType
