# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceClaimType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1alpha3_resource_claim_spec import V1alpha3ResourceClaimSpecType
from kubernetes_typed.client.models.v1alpha3_resource_claim_status import V1alpha3ResourceClaimStatusType


@dataclass
class V1alpha3ResourceClaimType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha3ResourceClaimSpecType
    status: V1alpha3ResourceClaimStatusType
