# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha1_storage_version import V1alpha1StorageVersionType


@dataclass
class V1alpha1StorageVersionListType:
    apiVersion: str
    items: List[V1alpha1StorageVersionType]
    kind: str
    metadata: V1ListMetaType
