# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1NamedRuleWithOperationsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1alpha1NamedRuleWithOperationsType:
    apiGroups: List[str]
    apiVersions: List[str]
    operations: List[str]
    resourceNames: List[str]
    resources: List[str]
    scope: str
