# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3BasicDeviceType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_device_attribute import V1alpha3DeviceAttributeType


@dataclass
class V1alpha3BasicDeviceType:
    attributes: Dict[str, V1alpha3DeviceAttributeType]
    capacity: Dict[str, str]
