# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceClaimTemplateType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha2_resource_claim_template_spec import V1alpha2ResourceClaimTemplateSpecType


@dataclass
class V1alpha2ResourceClaimTemplateType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha2ResourceClaimTemplateSpecType
