# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3PodSchedulingContextListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha3_pod_scheduling_context import V1alpha3PodSchedulingContextType


@dataclass
class V1alpha3PodSchedulingContextListType:
    apiVersion: str
    items: List[V1alpha3PodSchedulingContextType]
    kind: str
    metadata: V1ListMetaType
