# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceRequestType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_device_selector import V1alpha3DeviceSelectorType


@dataclass
class V1alpha3DeviceRequestType:
    adminAccess: bool
    allocationMode: str
    count: int
    deviceClassName: str
    name: str
    selectors: List[V1alpha3DeviceSelectorType]
