# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1TypeCheckingType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha1_expression_warning import V1alpha1ExpressionWarningType


@dataclass
class V1alpha1TypeCheckingType:
    expressionWarnings: List[V1alpha1ExpressionWarningType]
