# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceClaimSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_device_claim import V1alpha3DeviceClaimType


@dataclass
class V1alpha3ResourceClaimSpecType:
    controller: str
    devices: V1alpha3DeviceClaimType
