# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionMigrationListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha1_storage_version_migration import V1alpha1StorageVersionMigrationType


@dataclass
class V1alpha1StorageVersionMigrationListType:
    apiVersion: str
    items: List[V1alpha1StorageVersionMigrationType]
    kind: str
    metadata: V1ListMetaType
