# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ServiceCIDRListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1alpha1_service_cidr import V1alpha1ServiceCIDRType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1alpha1ServiceCIDRListType:
    api_version: str
    items: List[V1alpha1ServiceCIDRType]
    kind: str
    metadata: V1ListMetaType
