# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ClusterTrustBundleSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1alpha1ClusterTrustBundleSpecType:
    signer_name: str
    trust_bundle: str
