# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceClaimType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_device_claim_configuration import V1alpha3DeviceClaimConfigurationType
from kubernetes_typed.client.models.v1alpha3_device_constraint import V1alpha3DeviceConstraintType
from kubernetes_typed.client.models.v1alpha3_device_request import V1alpha3DeviceRequestType


@dataclass
class V1alpha3DeviceClaimType:
    config: List[V1alpha3DeviceClaimConfigurationType]
    constraints: List[V1alpha3DeviceConstraintType]
    requests: List[V1alpha3DeviceRequestType]
