# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ServerStorageVersionType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1alpha1ServerStorageVersionType:
    apiServerID: str
    decodableVersions: List[str]
    encodingVersion: str
    servedVersions: List[str]
