# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ClusterTrustBundleListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1alpha1_cluster_trust_bundle import V1alpha1ClusterTrustBundleType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1alpha1ClusterTrustBundleListType:
    api_version: str
    items: List[V1alpha1ClusterTrustBundleType]
    kind: str
    metadata: V1ListMetaType
