# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1LeaseCandidateListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha1_lease_candidate import V1alpha1LeaseCandidateType


@dataclass
class V1alpha1LeaseCandidateListType:
    apiVersion: str
    items: List[V1alpha1LeaseCandidateType]
    kind: str
    metadata: V1ListMetaType
