# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ParamRefType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorType


@dataclass
class V1alpha1ParamRefType:
    name: str
    namespace: str
    parameterNotFoundAction: str
    selector: V1LabelSelectorType
