# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_basic_device import V1alpha3BasicDeviceType


@dataclass
class V1alpha3DeviceType:
    basic: V1alpha3BasicDeviceType
    name: str
