# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionMigrationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1alpha1_storage_version_migration_spec import V1alpha1StorageVersionMigrationSpecType
from kubernetes_typed.client.models.v1alpha1_storage_version_migration_status import V1alpha1StorageVersionMigrationStatusType


@dataclass
class V1alpha1StorageVersionMigrationType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha1StorageVersionMigrationSpecType
    status: V1alpha1StorageVersionMigrationStatusType
