# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1VolumeAttributesClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1alpha1_volume_attributes_class import V1alpha1VolumeAttributesClassType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1alpha1VolumeAttributesClassListType:
    api_version: str
    items: List[V1alpha1VolumeAttributesClassType]
    kind: str
    metadata: V1ListMetaType
