# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ValidatingAdmissionPolicyStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_condition import V1ConditionType
from .v1alpha1_type_checking import V1alpha1TypeCheckingType


@dataclass
class V1alpha1ValidatingAdmissionPolicyStatusType:
    conditions: List[V1ConditionType]
    observed_generation: int
    type_checking: V1alpha1TypeCheckingType
