# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2PodSchedulingContextType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha2_pod_scheduling_context_spec import V1alpha2PodSchedulingContextSpecType
from .v1alpha2_pod_scheduling_context_status import V1alpha2PodSchedulingContextStatusType


@dataclass
class V1alpha2PodSchedulingContextType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha2PodSchedulingContextSpecType
    status: V1alpha2PodSchedulingContextStatusType
