# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha1_storage_version_status import V1alpha1StorageVersionStatusType


@dataclass
class V1alpha1StorageVersionType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: object
    status: V1alpha1StorageVersionStatusType
