# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2PodSchedulingContextSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1alpha2PodSchedulingContextSpecType:
    potential_nodes: List[str]
    selected_node: str
