# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceHandleType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1alpha2ResourceHandleType:
    data: str
    driver_name: str
