# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3PodSchedulingContextType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1alpha3_pod_scheduling_context_spec import V1alpha3PodSchedulingContextSpecType
from kubernetes_typed.client.models.v1alpha3_pod_scheduling_context_status import V1alpha3PodSchedulingContextStatusType


@dataclass
class V1alpha3PodSchedulingContextType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha3PodSchedulingContextSpecType
    status: V1alpha3PodSchedulingContextStatusType
