# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ServiceCIDRType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha1_service_cidr_spec import V1alpha1ServiceCIDRSpecType
from .v1alpha1_service_cidr_status import V1alpha1ServiceCIDRStatusType


@dataclass
class V1alpha1ServiceCIDRType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha1ServiceCIDRSpecType
    status: V1alpha1ServiceCIDRStatusType
