# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ValidatingAdmissionPolicyBindingType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1alpha1_validating_admission_policy_binding_spec import V1alpha1ValidatingAdmissionPolicyBindingSpecType


@dataclass
class V1alpha1ValidatingAdmissionPolicyBindingType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha1ValidatingAdmissionPolicyBindingSpecType
