# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ValidatingAdmissionPolicySpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha1_audit_annotation import V1alpha1AuditAnnotationType
from kubernetes_typed.client.models.v1alpha1_match_condition import V1alpha1MatchConditionType
from kubernetes_typed.client.models.v1alpha1_match_resources import V1alpha1MatchResourcesType
from kubernetes_typed.client.models.v1alpha1_param_kind import V1alpha1ParamKindType
from kubernetes_typed.client.models.v1alpha1_validation import V1alpha1ValidationType
from kubernetes_typed.client.models.v1alpha1_variable import V1alpha1VariableType


@dataclass
class V1alpha1ValidatingAdmissionPolicySpecType:
    auditAnnotations: List[V1alpha1AuditAnnotationType]
    failurePolicy: str
    matchConditions: List[V1alpha1MatchConditionType]
    matchConstraints: V1alpha1MatchResourcesType
    paramKind: V1alpha1ParamKindType
    validations: List[V1alpha1ValidationType]
    variables: List[V1alpha1VariableType]
