# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceClassSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_node_selector import V1NodeSelectorType
from kubernetes_typed.client.models.v1alpha3_device_class_configuration import V1alpha3DeviceClassConfigurationType
from kubernetes_typed.client.models.v1alpha3_device_selector import V1alpha3DeviceSelectorType


@dataclass
class V1alpha3DeviceClassSpecType:
    config: List[V1alpha3DeviceClassConfigurationType]
    selectors: List[V1alpha3DeviceSelectorType]
    suitableNodes: V1NodeSelectorType
