# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1LeaseCandidateSpecType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from typing import List

from dataclasses import dataclass


@dataclass
class V1alpha1LeaseCandidateSpecType:
    binaryVersion: str
    emulationVersion: str
    leaseName: str
    pingTime: datetime.datetime
    preferredStrategies: List[str]
    renewTime: datetime.datetime
