# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ValidatingAdmissionPolicyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha1_validating_admission_policy_spec import V1alpha1ValidatingAdmissionPolicySpecType
from .v1alpha1_validating_admission_policy_status import V1alpha1ValidatingAdmissionPolicyStatusType


@dataclass
class V1alpha1ValidatingAdmissionPolicyType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha1ValidatingAdmissionPolicySpecType
    status: V1alpha1ValidatingAdmissionPolicyStatusType
