# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1alpha1_storage_version_condition import V1alpha1StorageVersionConditionType
from .v1alpha1_server_storage_version import V1alpha1ServerStorageVersionType


@dataclass
class V1alpha1StorageVersionStatusType:
    common_encoding_version: str
    conditions: List[V1alpha1StorageVersionConditionType]
    storage_versions: List[V1alpha1ServerStorageVersionType]
