# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceSelectorType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_cel_device_selector import V1alpha3CELDeviceSelectorType


@dataclass
class V1alpha3DeviceSelectorType:
    cel: V1alpha3CELDeviceSelectorType
