# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceAllocationConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_opaque_device_configuration import V1alpha3OpaqueDeviceConfigurationType


@dataclass
class V1alpha3DeviceAllocationConfigurationType:
    opaque: V1alpha3OpaqueDeviceConfigurationType
    requests: List[str]
    source: str
