# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ClusterTrustBundleListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha1_cluster_trust_bundle import V1alpha1ClusterTrustBundleType


@dataclass
class V1alpha1ClusterTrustBundleListType:
    apiVersion: str
    items: List[V1alpha1ClusterTrustBundleType]
    kind: str
    metadata: V1ListMetaType
