# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ValidatingAdmissionPolicyStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_condition import V1ConditionType
from kubernetes_typed.client.models.v1alpha1_type_checking import V1alpha1TypeCheckingType


@dataclass
class V1alpha1ValidatingAdmissionPolicyStatusType:
    conditions: List[V1ConditionType]
    observedGeneration: int
    typeChecking: V1alpha1TypeCheckingType
