# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1SelfSubjectReviewStatusType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_user_info import V1UserInfoType


@dataclass
class V1alpha1SelfSubjectReviewStatusType:
    userInfo: V1UserInfoType
