# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceClaimTemplateSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1alpha2_resource_claim_spec import V1alpha2ResourceClaimSpecType


@dataclass
class V1alpha2ResourceClaimTemplateSpecType:
    metadata: V1ObjectMetaType
    spec: V1alpha2ResourceClaimSpecType
