# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceClaimTemplateListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha3_resource_claim_template import V1alpha3ResourceClaimTemplateType


@dataclass
class V1alpha3ResourceClaimTemplateListType:
    apiVersion: str
    items: List[V1alpha3ResourceClaimTemplateType]
    kind: str
    metadata: V1ListMetaType
