# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceClassConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha3_opaque_device_configuration import V1alpha3OpaqueDeviceConfigurationType


@dataclass
class V1alpha3DeviceClassConfigurationType:
    opaque: V1alpha3OpaqueDeviceConfigurationType
