# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ValidatingAdmissionPolicyBindingSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1alpha1_match_resources import V1alpha1MatchResourcesType
from .v1alpha1_param_ref import V1alpha1ParamRefType


@dataclass
class V1alpha1ValidatingAdmissionPolicyBindingSpecType:
    match_resources: V1alpha1MatchResourcesType
    param_ref: V1alpha1ParamRefType
    policy_name: str
    validation_actions: List[str]
