# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceClaimSchedulingStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1alpha3ResourceClaimSchedulingStatusType:
    name: str
    unsuitableNodes: List[str]
