# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionMigrationStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha1_migration_condition import V1alpha1MigrationConditionType


@dataclass
class V1alpha1StorageVersionMigrationStatusType:
    conditions: List[V1alpha1MigrationConditionType]
    resourceVersion: str
