# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ValidatingAdmissionPolicyBindingSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha1_match_resources import V1alpha1MatchResourcesType
from kubernetes_typed.client.models.v1alpha1_param_ref import V1alpha1ParamRefType


@dataclass
class V1alpha1ValidatingAdmissionPolicyBindingSpecType:
    matchResources: V1alpha1MatchResourcesType
    paramRef: V1alpha1ParamRefType
    policyName: str
    validationActions: List[str]
