# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3DeviceClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1alpha3_device_class import V1alpha3DeviceClassType


@dataclass
class V1alpha3DeviceClassListType:
    apiVersion: str
    items: List[V1alpha3DeviceClassType]
    kind: str
    metadata: V1ListMetaType
