# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha3ResourceSliceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1alpha3_resource_slice_spec import V1alpha3ResourceSliceSpecType


@dataclass
class V1alpha3ResourceSliceType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1alpha3ResourceSliceSpecType
