# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha2ResourceClassParametersReferenceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1alpha2ResourceClassParametersReferenceType:
    api_group: str
    kind: str
    name: str
    namespace: str
