# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ServiceCIDRStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_condition import V1ConditionType


@dataclass
class V1alpha1ServiceCIDRStatusType:
    conditions: List[V1ConditionType]
