# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha1_server_storage_version import V1alpha1ServerStorageVersionType
from kubernetes_typed.client.models.v1alpha1_storage_version_condition import V1alpha1StorageVersionConditionType


@dataclass
class V1alpha1StorageVersionStatusType:
    commonEncodingVersion: str
    conditions: List[V1alpha1StorageVersionConditionType]
    storageVersions: List[V1alpha1ServerStorageVersionType]
