# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ServiceCIDRSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List


@dataclass
class V1alpha1ServiceCIDRSpecType:
    cidrs: List[str]
