# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionMigrationSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1alpha1_group_version_resource import V1alpha1GroupVersionResourceType


@dataclass
class V1alpha1StorageVersionMigrationSpecType:
    continueToken: str
    resource: V1alpha1GroupVersionResourceType
