# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicyType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1beta1_validating_admission_policy_spec import V1beta1ValidatingAdmissionPolicySpecType
from .v1beta1_validating_admission_policy_status import V1beta1ValidatingAdmissionPolicyStatusType


@dataclass
class V1beta1ValidatingAdmissionPolicyType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1beta1ValidatingAdmissionPolicySpecType
    status: V1beta1ValidatingAdmissionPolicyStatusType
