# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3PriorityLevelConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1beta3_priority_level_configuration_spec import V1beta3PriorityLevelConfigurationSpecType
from .v1beta3_priority_level_configuration_status import V1beta3PriorityLevelConfigurationStatusType


@dataclass
class V1beta3PriorityLevelConfigurationType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1beta3PriorityLevelConfigurationSpecType
    status: V1beta3PriorityLevelConfigurationStatusType
