# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ParamRefType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1beta1ParamRefType:
    name: str
    namespace: str
    parameter_not_found_action: str
    selector: V1LabelSelectorType
