# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicyBindingSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1beta1_match_resources import V1beta1MatchResourcesType
from kubernetes_typed.client.models.v1beta1_param_ref import V1beta1ParamRefType


@dataclass
class V1beta1ValidatingAdmissionPolicyBindingSpecType:
    matchResources: V1beta1MatchResourcesType
    paramRef: V1beta1ParamRefType
    policyName: str
    validationActions: List[str]
