# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicySpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1beta1_audit_annotation import V1beta1AuditAnnotationType
from kubernetes_typed.client.models.v1beta1_match_condition import V1beta1MatchConditionType
from kubernetes_typed.client.models.v1beta1_match_resources import V1beta1MatchResourcesType
from kubernetes_typed.client.models.v1beta1_param_kind import V1beta1ParamKindType
from kubernetes_typed.client.models.v1beta1_validation import V1beta1ValidationType
from kubernetes_typed.client.models.v1beta1_variable import V1beta1VariableType


@dataclass
class V1beta1ValidatingAdmissionPolicySpecType:
    auditAnnotations: List[V1beta1AuditAnnotationType]
    failurePolicy: str
    matchConditions: List[V1beta1MatchConditionType]
    matchConstraints: V1beta1MatchResourcesType
    paramKind: V1beta1ParamKindType
    validations: List[V1beta1ValidationType]
    variables: List[V1beta1VariableType]
