# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1IPAddressType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1beta1_ip_address_spec import V1beta1IPAddressSpecType


@dataclass
class V1beta1IPAddressType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1beta1IPAddressSpecType
