# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3FlowSchemaStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta3_flow_schema_condition import V1beta3FlowSchemaConditionType


@dataclass
class V1beta3FlowSchemaStatusType:
    conditions: List[V1beta3FlowSchemaConditionType]
