# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1MatchResourcesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta1_named_rule_with_operations import V1beta1NamedRuleWithOperationsType
from .v1_label_selector import V1LabelSelectorType


@dataclass
class V1beta1MatchResourcesType:
    exclude_resource_rules: List[V1beta1NamedRuleWithOperationsType]
    match_policy: str
    namespace_selector: V1LabelSelectorType
    object_selector: V1LabelSelectorType
    resource_rules: List[V1beta1NamedRuleWithOperationsType]
