# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3PriorityLevelConfigurationSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1beta3_exempt_priority_level_configuration import V1beta3ExemptPriorityLevelConfigurationType
from .v1beta3_limited_priority_level_configuration import V1beta3LimitedPriorityLevelConfigurationType


@dataclass
class V1beta3PriorityLevelConfigurationSpecType:
    exempt: V1beta3ExemptPriorityLevelConfigurationType
    limited: V1beta3LimitedPriorityLevelConfigurationType
    type: str
