# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1beta1ValidationType:
    expression: str
    message: str
    message_expression: str
    reason: str
