# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1AuditAnnotationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1beta1AuditAnnotationType:
    key: str
    value_expression: str
