# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ServiceCIDRSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1beta1ServiceCIDRSpecType:
    cidrs: List[str]
