# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicyBindingSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta1_match_resources import V1beta1MatchResourcesType
from .v1beta1_param_ref import V1beta1ParamRefType


@dataclass
class V1beta1ValidatingAdmissionPolicyBindingSpecType:
    match_resources: V1beta1MatchResourcesType
    param_ref: V1beta1ParamRefType
    policy_name: str
    validation_actions: List[str]
