# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicyBindingListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta1_validating_admission_policy_binding import V1beta1ValidatingAdmissionPolicyBindingType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1beta1ValidatingAdmissionPolicyBindingListType:
    api_version: str
    items: List[V1beta1ValidatingAdmissionPolicyBindingType]
    kind: str
    metadata: V1ListMetaType
