# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3PolicyRulesWithSubjectsType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1beta3_non_resource_policy_rule import V1beta3NonResourcePolicyRuleType
from kubernetes_typed.client.models.v1beta3_resource_policy_rule import V1beta3ResourcePolicyRuleType
from kubernetes_typed.client.models.v1beta3_subject import V1beta3SubjectType


@dataclass
class V1beta3PolicyRulesWithSubjectsType:
    nonResourceRules: List[V1beta3NonResourcePolicyRuleType]
    resourceRules: List[V1beta3ResourcePolicyRuleType]
    subjects: List[V1beta3SubjectType]
