# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicyStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1_condition import V1ConditionType
from .v1beta1_type_checking import V1beta1TypeCheckingType


@dataclass
class V1beta1ValidatingAdmissionPolicyStatusType:
    conditions: List[V1ConditionType]
    observed_generation: int
    type_checking: V1beta1TypeCheckingType
