# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3PolicyRulesWithSubjectsType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta3_non_resource_policy_rule import V1beta3NonResourcePolicyRuleType
from .v1beta3_resource_policy_rule import V1beta3ResourcePolicyRuleType
from .v1beta3_subject import V1beta3SubjectType


@dataclass
class V1beta3PolicyRulesWithSubjectsType:
    non_resource_rules: List[V1beta3NonResourcePolicyRuleType]
    resource_rules: List[V1beta3ResourcePolicyRuleType]
    subjects: List[V1beta3SubjectType]
