# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1VolumeAttributesClassListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1beta1_volume_attributes_class import V1beta1VolumeAttributesClassType


@dataclass
class V1beta1VolumeAttributesClassListType:
    apiVersion: str
    items: List[V1beta1VolumeAttributesClassType]
    kind: str
    metadata: V1ListMetaType
