# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ServiceCIDRListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1beta1_service_cidr import V1beta1ServiceCIDRType


@dataclass
class V1beta1ServiceCIDRListType:
    apiVersion: str
    items: List[V1beta1ServiceCIDRType]
    kind: str
    metadata: V1ListMetaType
