# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3FlowSchemaType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v1beta3_flow_schema_spec import V1beta3FlowSchemaSpecType
from .v1beta3_flow_schema_status import V1beta3FlowSchemaStatusType


@dataclass
class V1beta3FlowSchemaType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1beta3FlowSchemaSpecType
    status: V1beta3FlowSchemaStatusType
