# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ExpressionWarningType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1beta1ExpressionWarningType:
    field_ref: str
    warning: str
