# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3PriorityLevelConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1beta3_priority_level_configuration import V1beta3PriorityLevelConfigurationType


@dataclass
class V1beta3PriorityLevelConfigurationListType:
    apiVersion: str
    items: List[V1beta3PriorityLevelConfigurationType]
    kind: str
    metadata: V1ListMetaType
