# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3LimitResponseType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1beta3_queuing_configuration import V1beta3QueuingConfigurationType


@dataclass
class V1beta3LimitResponseType:
    queuing: V1beta3QueuingConfigurationType
    type: str
