# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ServiceCIDRType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v1beta1_service_cidr_spec import V1beta1ServiceCIDRSpecType
from kubernetes_typed.client.models.v1beta1_service_cidr_status import V1beta1ServiceCIDRStatusType


@dataclass
class V1beta1ServiceCIDRType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V1beta1ServiceCIDRSpecType
    status: V1beta1ServiceCIDRStatusType
