# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3FlowSchemaSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1beta3_flow_distinguisher_method import V1beta3FlowDistinguisherMethodType
from kubernetes_typed.client.models.v1beta3_policy_rules_with_subjects import V1beta3PolicyRulesWithSubjectsType
from kubernetes_typed.client.models.v1beta3_priority_level_configuration_reference import V1beta3PriorityLevelConfigurationReferenceType


@dataclass
class V1beta3FlowSchemaSpecType:
    distinguisherMethod: V1beta3FlowDistinguisherMethodType
    matchingPrecedence: int
    priorityLevelConfiguration: V1beta3PriorityLevelConfigurationReferenceType
    rules: List[V1beta3PolicyRulesWithSubjectsType]
