# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1IPAddressSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1beta1_parent_reference import V1beta1ParentReferenceType


@dataclass
class V1beta1IPAddressSpecType:
    parentRef: V1beta1ParentReferenceType
