# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3FlowSchemaConditionType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime


from dataclasses import dataclass


@dataclass
class V1beta3FlowSchemaConditionType:
    lastTransitionTime: datetime.datetime
    message: str
    reason: str
    status: str
    type: str
