# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3FlowSchemaSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta3_flow_distinguisher_method import V1beta3FlowDistinguisherMethodType
from .v1beta3_priority_level_configuration_reference import V1beta3PriorityLevelConfigurationReferenceType
from .v1beta3_policy_rules_with_subjects import V1beta3PolicyRulesWithSubjectsType


@dataclass
class V1beta3FlowSchemaSpecType:
    distinguisher_method: V1beta3FlowDistinguisherMethodType
    matching_precedence: int
    priority_level_configuration: V1beta3PriorityLevelConfigurationReferenceType
    rules: List[V1beta3PolicyRulesWithSubjectsType]
