# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3LimitedPriorityLevelConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1beta3_limit_response import V1beta3LimitResponseType


@dataclass
class V1beta3LimitedPriorityLevelConfigurationType:
    borrowingLimitPercent: int
    lendablePercent: int
    limitResponse: V1beta3LimitResponseType
    nominalConcurrencyShares: int
