# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3PriorityLevelConfigurationStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta3_priority_level_configuration_condition import V1beta3PriorityLevelConfigurationConditionType


@dataclass
class V1beta3PriorityLevelConfigurationStatusType:
    conditions: List[V1beta3PriorityLevelConfigurationConditionType]
