# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1VolumeAttributesClassType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import Dict

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType


@dataclass
class V1beta1VolumeAttributesClassType:
    apiVersion: str
    driverName: str
    kind: str
    metadata: V1ObjectMetaType
    parameters: Dict[str, str]
