# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3FlowSchemaListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta3_flow_schema import V1beta3FlowSchemaType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1beta3FlowSchemaListType:
    api_version: str
    items: List[V1beta3FlowSchemaType]
    kind: str
    metadata: V1ListMetaType
