# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3QueuingConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1beta3QueuingConfigurationType:
    hand_size: int
    queue_length_limit: int
    queues: int
