# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3FlowSchemaListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1beta3_flow_schema import V1beta3FlowSchemaType


@dataclass
class V1beta3FlowSchemaListType:
    apiVersion: str
    items: List[V1beta3FlowSchemaType]
    kind: str
    metadata: V1ListMetaType
