# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3ResourcePolicyRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1beta3ResourcePolicyRuleType:
    apiGroups: List[str]
    clusterScope: bool
    namespaces: List[str]
    resources: List[str]
    verbs: List[str]
