# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ServiceCIDRStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_condition import V1ConditionType


@dataclass
class V1beta1ServiceCIDRStatusType:
    conditions: List[V1ConditionType]
