# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1TypeCheckingType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1beta1_expression_warning import V1beta1ExpressionWarningType


@dataclass
class V1beta1TypeCheckingType:
    expressionWarnings: List[V1beta1ExpressionWarningType]
