# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3ExemptPriorityLevelConfigurationType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V1beta3ExemptPriorityLevelConfigurationType:
    lendable_percent: int
    nominal_concurrency_shares: int
