# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3PriorityLevelConfigurationListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta3_priority_level_configuration import V1beta3PriorityLevelConfigurationType
from .v1_list_meta import V1ListMetaType


@dataclass
class V1beta3PriorityLevelConfigurationListType:
    api_version: str
    items: List[V1beta3PriorityLevelConfigurationType]
    kind: str
    metadata: V1ListMetaType
