# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicySpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v1beta1_audit_annotation import V1beta1AuditAnnotationType
from .v1beta1_match_condition import V1beta1MatchConditionType
from .v1beta1_match_resources import V1beta1MatchResourcesType
from .v1beta1_param_kind import V1beta1ParamKindType
from .v1beta1_validation import V1beta1ValidationType
from .v1beta1_variable import V1beta1VariableType


@dataclass
class V1beta1ValidatingAdmissionPolicySpecType:
    audit_annotations: List[V1beta1AuditAnnotationType]
    failure_policy: str
    match_conditions: List[V1beta1MatchConditionType]
    match_constraints: V1beta1MatchResourcesType
    param_kind: V1beta1ParamKindType
    validations: List[V1beta1ValidationType]
    variables: List[V1beta1VariableType]
