# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1IPAddressListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v1beta1_ip_address import V1beta1IPAddressType


@dataclass
class V1beta1IPAddressListType:
    apiVersion: str
    items: List[V1beta1IPAddressType]
    kind: str
    metadata: V1ListMetaType
