# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta3NonResourcePolicyRuleType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass


@dataclass
class V1beta3NonResourcePolicyRuleType:
    nonResourceURLs: List[str]
    verbs: List[str]
