# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingAdmissionPolicyStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_condition import V1ConditionType
from kubernetes_typed.client.models.v1beta1_type_checking import V1beta1TypeCheckingType


@dataclass
class V1beta1ValidatingAdmissionPolicyStatusType:
    conditions: List[V1ConditionType]
    observedGeneration: int
    typeChecking: V1beta1TypeCheckingType
