# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2CrossVersionObjectReferenceType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V2CrossVersionObjectReferenceType:
    apiVersion: str
    kind: str
    name: str
