# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ExternalMetricStatusType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v2_metric_identifier import V2MetricIdentifierType
from kubernetes_typed.client.models.v2_metric_value_status import V2MetricValueStatusType


@dataclass
class V2ExternalMetricStatusType:
    current: V2MetricValueStatusType
    metric: V2MetricIdentifierType
