# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ExternalMetricSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v2_metric_identifier import V2MetricIdentifierType
from .v2_metric_target import V2MetricTargetType


@dataclass
class V2ExternalMetricSourceType:
    metric: V2MetricIdentifierType
    target: V2MetricTargetType
