# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaType
from kubernetes_typed.client.models.v2_horizontal_pod_autoscaler_spec import V2HorizontalPodAutoscalerSpecType
from kubernetes_typed.client.models.v2_horizontal_pod_autoscaler_status import V2HorizontalPodAutoscalerStatusType


@dataclass
class V2HorizontalPodAutoscalerType:
    apiVersion: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V2HorizontalPodAutoscalerSpecType
    status: V2HorizontalPodAutoscalerStatusType
