# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v2_cross_version_object_reference import V2CrossVersionObjectReferenceType
from kubernetes_typed.client.models.v2_horizontal_pod_autoscaler_behavior import V2HorizontalPodAutoscalerBehaviorType
from kubernetes_typed.client.models.v2_metric_spec import V2MetricSpecType


@dataclass
class V2HorizontalPodAutoscalerSpecType:
    behavior: V2HorizontalPodAutoscalerBehaviorType
    maxReplicas: int
    metrics: List[V2MetricSpecType]
    minReplicas: int
    scaleTargetRef: V2CrossVersionObjectReferenceType
