# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerBehaviorType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v2_hpa_scaling_rules import V2HPAScalingRulesType


@dataclass
class V2HorizontalPodAutoscalerBehaviorType:
    scaleDown: V2HPAScalingRulesType
    scaleUp: V2HPAScalingRulesType
