# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerBehaviorType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v2_hpa_scaling_rules import V2HPAScalingRulesType


@dataclass
class V2HorizontalPodAutoscalerBehaviorType:
    scale_down: V2HPAScalingRulesType
    scale_up: V2HPAScalingRulesType
