# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HPAScalingRulesType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v2_hpa_scaling_policy import V2HPAScalingPolicyType


@dataclass
class V2HPAScalingRulesType:
    policies: List[V2HPAScalingPolicyType]
    select_policy: str
    stabilization_window_seconds: int
