# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerListType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass
from typing import List

from .v2_horizontal_pod_autoscaler import V2HorizontalPodAutoscalerType
from .v1_list_meta import V1ListMetaType


@dataclass
class V2HorizontalPodAutoscalerListType:
    api_version: str
    items: List[V2HorizontalPodAutoscalerType]
    kind: str
    metadata: V1ListMetaType
