# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerListType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaType
from kubernetes_typed.client.models.v2_horizontal_pod_autoscaler import V2HorizontalPodAutoscalerType


@dataclass
class V2HorizontalPodAutoscalerListType:
    apiVersion: str
    items: List[V2HorizontalPodAutoscalerType]
    kind: str
    metadata: V1ListMetaType
