# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v1_object_meta import V1ObjectMetaType
from .v2_horizontal_pod_autoscaler_spec import V2HorizontalPodAutoscalerSpecType
from .v2_horizontal_pod_autoscaler_status import V2HorizontalPodAutoscalerStatusType


@dataclass
class V2HorizontalPodAutoscalerType:
    api_version: str
    kind: str
    metadata: V1ObjectMetaType
    spec: V2HorizontalPodAutoscalerSpecType
    status: V2HorizontalPodAutoscalerStatusType
