# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HPAScalingRulesType generated type."""
# pylint: disable=too-many-instance-attributes
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v2_hpa_scaling_policy import V2HPAScalingPolicyType


@dataclass
class V2HPAScalingRulesType:
    policies: List[V2HPAScalingPolicyType]
    selectPolicy: str
    stabilizationWindowSeconds: int
