# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerStatusType generated type."""
# pylint: disable=too-many-instance-attributes
import datetime
from typing import List

from dataclasses import dataclass
from kubernetes_typed.client.models.v2_horizontal_pod_autoscaler_condition import V2HorizontalPodAutoscalerConditionType
from kubernetes_typed.client.models.v2_metric_status import V2MetricStatusType


@dataclass
class V2HorizontalPodAutoscalerStatusType:
    conditions: List[V2HorizontalPodAutoscalerConditionType]
    currentMetrics: List[V2MetricStatusType]
    currentReplicas: int
    desiredReplicas: int
    lastScaleTime: datetime.datetime
    observedGeneration: int
