# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricStatusType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v2_container_resource_metric_status import V2ContainerResourceMetricStatusType
from kubernetes_typed.client.models.v2_external_metric_status import V2ExternalMetricStatusType
from kubernetes_typed.client.models.v2_object_metric_status import V2ObjectMetricStatusType
from kubernetes_typed.client.models.v2_pods_metric_status import V2PodsMetricStatusType
from kubernetes_typed.client.models.v2_resource_metric_status import V2ResourceMetricStatusType


@dataclass
class V2MetricStatusType:
    containerResource: V2ContainerResourceMetricStatusType
    external: V2ExternalMetricStatusType
    object: V2ObjectMetricStatusType
    pods: V2PodsMetricStatusType
    resource: V2ResourceMetricStatusType
    type: str
