# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricTargetType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass


@dataclass
class V2MetricTargetType:
    averageUtilization: int
    averageValue: str
    type: str
    value: str
