# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricSpecType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v2_container_resource_metric_source import V2ContainerResourceMetricSourceType
from .v2_external_metric_source import V2ExternalMetricSourceType
from .v2_object_metric_source import V2ObjectMetricSourceType
from .v2_pods_metric_source import V2PodsMetricSourceType
from .v2_resource_metric_source import V2ResourceMetricSourceType


@dataclass
class V2MetricSpecType:
    container_resource: V2ContainerResourceMetricSourceType
    external: V2ExternalMetricSourceType
    object: V2ObjectMetricSourceType
    pods: V2PodsMetricSourceType
    resource: V2ResourceMetricSourceType
    type: str
