# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricSpecType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v2_container_resource_metric_source import V2ContainerResourceMetricSourceType
from kubernetes_typed.client.models.v2_external_metric_source import V2ExternalMetricSourceType
from kubernetes_typed.client.models.v2_object_metric_source import V2ObjectMetricSourceType
from kubernetes_typed.client.models.v2_pods_metric_source import V2PodsMetricSourceType
from kubernetes_typed.client.models.v2_resource_metric_source import V2ResourceMetricSourceType


@dataclass
class V2MetricSpecType:
    containerResource: V2ContainerResourceMetricSourceType
    external: V2ExternalMetricSourceType
    object: V2ObjectMetricSourceType
    pods: V2PodsMetricSourceType
    resource: V2ResourceMetricSourceType
    type: str
