# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricTargetType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V2MetricTargetType:
    average_utilization: int
    average_value: str
    type: str
    value: str
