# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricValueStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


@dataclass
class V2MetricValueStatusType:
    average_utilization: int
    average_value: str
    value: str
