# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ObjectMetricStatusType generated type."""
# pylint: disable=too-many-instance-attributes


from dataclasses import dataclass
from kubernetes_typed.client.models.v2_cross_version_object_reference import V2CrossVersionObjectReferenceType
from kubernetes_typed.client.models.v2_metric_identifier import V2MetricIdentifierType
from kubernetes_typed.client.models.v2_metric_value_status import V2MetricValueStatusType


@dataclass
class V2ObjectMetricStatusType:
    current: V2MetricValueStatusType
    describedObject: V2CrossVersionObjectReferenceType
    metric: V2MetricIdentifierType
