# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ObjectMetricStatusType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v2_metric_value_status import V2MetricValueStatusType
from .v2_cross_version_object_reference import V2CrossVersionObjectReferenceType
from .v2_metric_identifier import V2MetricIdentifierType


@dataclass
class V2ObjectMetricStatusType:
    current: V2MetricValueStatusType
    described_object: V2CrossVersionObjectReferenceType
    metric: V2MetricIdentifierType
