# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ObjectMetricSourceType generated type."""
# pylint: disable=too-many-instance-attributes
from dataclasses import dataclass


from .v2_cross_version_object_reference import V2CrossVersionObjectReferenceType
from .v2_metric_identifier import V2MetricIdentifierType
from .v2_metric_target import V2MetricTargetType


@dataclass
class V2ObjectMetricSourceType:
    described_object: V2CrossVersionObjectReferenceType
    metric: V2MetricIdentifierType
    target: V2MetricTargetType
